<?php
/**
 * CreatePersonRequestTimeRecording
 *
 * PHP version 8.1
 *
 * @package  TimecardClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * timeCard REST facade
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.2
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TimecardClient\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use TimecardClient\ObjectSerializer;

/**
 * CreatePersonRequestTimeRecording Class Doc Comment
 *
 * @package  TimecardClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class CreatePersonRequestTimeRecording implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'createPerson_request_timeRecording';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'validFrom' => 'string',
        'workingProfileId' => 'int',
        'calculationTemplateIds' => 'int[]',
        'holidayProfileId' => 'int',
        'holidayDaysPerYear' => 'float',
        'firstDayOfMonth' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'validFrom' => null,
        'workingProfileId' => null,
        'calculationTemplateIds' => null,
        'holidayProfileId' => null,
        'holidayDaysPerYear' => null,
        'firstDayOfMonth' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'validFrom' => false,
        'workingProfileId' => false,
        'calculationTemplateIds' => false,
        'holidayProfileId' => false,
        'holidayDaysPerYear' => false,
        'firstDayOfMonth' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'validFrom' => 'validFrom',
        'workingProfileId' => 'workingProfileId',
        'calculationTemplateIds' => 'calculationTemplateIds',
        'holidayProfileId' => 'holidayProfileId',
        'holidayDaysPerYear' => 'holidayDaysPerYear',
        'firstDayOfMonth' => 'firstDayOfMonth'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'validFrom' => 'setValidFrom',
        'workingProfileId' => 'setWorkingProfileId',
        'calculationTemplateIds' => 'setCalculationTemplateIds',
        'holidayProfileId' => 'setHolidayProfileId',
        'holidayDaysPerYear' => 'setHolidayDaysPerYear',
        'firstDayOfMonth' => 'setFirstDayOfMonth'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'validFrom' => 'getValidFrom',
        'workingProfileId' => 'getWorkingProfileId',
        'calculationTemplateIds' => 'getCalculationTemplateIds',
        'holidayProfileId' => 'getHolidayProfileId',
        'holidayDaysPerYear' => 'getHolidayDaysPerYear',
        'firstDayOfMonth' => 'getFirstDayOfMonth'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('validFrom', $data ?? [], null);
        $this->setIfExists('workingProfileId', $data ?? [], null);
        $this->setIfExists('calculationTemplateIds', $data ?? [], null);
        $this->setIfExists('holidayProfileId', $data ?? [], null);
        $this->setIfExists('holidayDaysPerYear', $data ?? [], null);
        $this->setIfExists('firstDayOfMonth', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if (!is_null($this->container['validFrom']) && !preg_match("/^\\d{4}-\\d{2}-\\d{2}$/", $this->container['validFrom'])) {
            $invalidProperties[] = "invalid value for 'validFrom', must be conform to the pattern /^\\d{4}-\\d{2}-\\d{2}$/.";
        }

        if (!is_null($this->container['workingProfileId']) && ($this->container['workingProfileId'] > 9007199254740991)) {
            $invalidProperties[] = "invalid value for 'workingProfileId', must be smaller than or equal to 9007199254740991.";
        }

        if (!is_null($this->container['calculationTemplateIds']) && (count($this->container['calculationTemplateIds']) < 1)) {
            $invalidProperties[] = "invalid value for 'calculationTemplateIds', number of items must be greater than or equal to 1.";
        }

        if (!is_null($this->container['holidayProfileId']) && ($this->container['holidayProfileId'] > 9007199254740991)) {
            $invalidProperties[] = "invalid value for 'holidayProfileId', must be smaller than or equal to 9007199254740991.";
        }

        if (!is_null($this->container['holidayDaysPerYear']) && ($this->container['holidayDaysPerYear'] > 366)) {
            $invalidProperties[] = "invalid value for 'holidayDaysPerYear', must be smaller than or equal to 366.";
        }

        if (!is_null($this->container['holidayDaysPerYear']) && ($this->container['holidayDaysPerYear'] < 0)) {
            $invalidProperties[] = "invalid value for 'holidayDaysPerYear', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['firstDayOfMonth']) && ($this->container['firstDayOfMonth'] > 28)) {
            $invalidProperties[] = "invalid value for 'firstDayOfMonth', must be smaller than or equal to 28.";
        }

        if (!is_null($this->container['firstDayOfMonth']) && ($this->container['firstDayOfMonth'] < 1)) {
            $invalidProperties[] = "invalid value for 'firstDayOfMonth', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets validFrom
     *
     * @return string|null
     */
    public function getValidFrom(): ?string
    {
        return $this->container['validFrom'];
    }

    /**
     * Sets validFrom
     *
     * @param string|null $validFrom valid-from date for changed profiles and accounts; defaults to today
     *
     * @return $this
     */
    public function setValidFrom(?string $validFrom): static
    {
        if (is_null($validFrom)) {
            throw new InvalidArgumentException('non-nullable validFrom cannot be null');
        }

        if ((!preg_match("/^\\d{4}-\\d{2}-\\d{2}$/", ObjectSerializer::toString($validFrom)))) {
            throw new InvalidArgumentException("invalid value for \$validFrom when calling CreatePersonRequestTimeRecording., must conform to the pattern /^\\d{4}-\\d{2}-\\d{2}$/.");
        }

        $this->container['validFrom'] = $validFrom;

        return $this;
    }

    /**
     * Gets workingProfileId
     *
     * @return int|null
     */
    public function getWorkingProfileId(): ?int
    {
        return $this->container['workingProfileId'];
    }

    /**
     * Sets workingProfileId
     *
     * @param int|null $workingProfileId workingProfileId
     *
     * @return $this
     */
    public function setWorkingProfileId(?int $workingProfileId): static
    {
        if (is_null($workingProfileId)) {
            throw new InvalidArgumentException('non-nullable workingProfileId cannot be null');
        }

        if (($workingProfileId > 9007199254740991)) {
            throw new InvalidArgumentException('invalid value for $workingProfileId when calling CreatePersonRequestTimeRecording., must be smaller than or equal to 9007199254740991.');
        }

        $this->container['workingProfileId'] = $workingProfileId;

        return $this;
    }

    /**
     * Gets calculationTemplateIds
     *
     * @return int[]|null
     */
    public function getCalculationTemplateIds(): ?array
    {
        return $this->container['calculationTemplateIds'];
    }

    /**
     * Sets calculationTemplateIds
     *
     * @param int[]|null $calculationTemplateIds calculationTemplateIds
     *
     * @return $this
     */
    public function setCalculationTemplateIds(?array $calculationTemplateIds): static
    {
        if (is_null($calculationTemplateIds)) {
            throw new InvalidArgumentException('non-nullable calculationTemplateIds cannot be null');
        }


        if ((count($calculationTemplateIds) < 1)) {
            throw new InvalidArgumentException('invalid length for $calculationTemplateIds when calling CreatePersonRequestTimeRecording., number of items must be greater than or equal to 1.');
        }
        $this->container['calculationTemplateIds'] = $calculationTemplateIds;

        return $this;
    }

    /**
     * Gets holidayProfileId
     *
     * @return int|null
     */
    public function getHolidayProfileId(): ?int
    {
        return $this->container['holidayProfileId'];
    }

    /**
     * Sets holidayProfileId
     *
     * @param int|null $holidayProfileId holidayProfileId
     *
     * @return $this
     */
    public function setHolidayProfileId(?int $holidayProfileId): static
    {
        if (is_null($holidayProfileId)) {
            throw new InvalidArgumentException('non-nullable holidayProfileId cannot be null');
        }

        if (($holidayProfileId > 9007199254740991)) {
            throw new InvalidArgumentException('invalid value for $holidayProfileId when calling CreatePersonRequestTimeRecording., must be smaller than or equal to 9007199254740991.');
        }

        $this->container['holidayProfileId'] = $holidayProfileId;

        return $this;
    }

    /**
     * Gets holidayDaysPerYear
     *
     * @return float|null
     */
    public function getHolidayDaysPerYear(): ?float
    {
        return $this->container['holidayDaysPerYear'];
    }

    /**
     * Sets holidayDaysPerYear
     *
     * @param float|null $holidayDaysPerYear holidayDaysPerYear
     *
     * @return $this
     */
    public function setHolidayDaysPerYear(?float $holidayDaysPerYear): static
    {
        if (is_null($holidayDaysPerYear)) {
            throw new InvalidArgumentException('non-nullable holidayDaysPerYear cannot be null');
        }

        if (($holidayDaysPerYear > 366)) {
            throw new InvalidArgumentException('invalid value for $holidayDaysPerYear when calling CreatePersonRequestTimeRecording., must be smaller than or equal to 366.');
        }
        if (($holidayDaysPerYear < 0)) {
            throw new InvalidArgumentException('invalid value for $holidayDaysPerYear when calling CreatePersonRequestTimeRecording., must be bigger than or equal to 0.');
        }

        $this->container['holidayDaysPerYear'] = $holidayDaysPerYear;

        return $this;
    }

    /**
     * Gets firstDayOfMonth
     *
     * @return int|null
     */
    public function getFirstDayOfMonth(): ?int
    {
        return $this->container['firstDayOfMonth'];
    }

    /**
     * Sets firstDayOfMonth
     *
     * @param int|null $firstDayOfMonth firstDayOfMonth
     *
     * @return $this
     */
    public function setFirstDayOfMonth(?int $firstDayOfMonth): static
    {
        if (is_null($firstDayOfMonth)) {
            throw new InvalidArgumentException('non-nullable firstDayOfMonth cannot be null');
        }

        if (($firstDayOfMonth > 28)) {
            throw new InvalidArgumentException('invalid value for $firstDayOfMonth when calling CreatePersonRequestTimeRecording., must be smaller than or equal to 28.');
        }
        if (($firstDayOfMonth < 1)) {
            throw new InvalidArgumentException('invalid value for $firstDayOfMonth when calling CreatePersonRequestTimeRecording., must be bigger than or equal to 1.');
        }

        $this->container['firstDayOfMonth'] = $firstDayOfMonth;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


