<?php
/**
 * CreateProject201Response
 *
 * PHP version 8.1
 *
 * @package  TimecardClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * timeCard REST facade
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.1
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TimecardClient\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use TimecardClient\ObjectSerializer;

/**
 * CreateProject201Response Class Doc Comment
 *
 * @package  TimecardClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class CreateProject201Response implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'createProject_201_response';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'id' => 'int',
        'name' => 'string',
        'token' => 'string',
        'number' => 'int',
        'description' => 'string',
        'end_date' => 'string',
        'is_active' => 'bool',
        'is_used' => 'bool',
        'work_operation_ids' => 'int[]',
        'restricted_department_ids' => 'int[]',
        'restricted_group_ids' => 'int[]',
        'browser_allowed' => 'bool',
        'terminal_allowed' => 'bool',
        'app_allowed' => 'bool',
        'free_fields' => '\TimecardClient\Model\CreatePerson201ResponseFreeFieldsInner[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'id' => null,
        'name' => null,
        'token' => null,
        'number' => null,
        'description' => null,
        'end_date' => null,
        'is_active' => null,
        'is_used' => null,
        'work_operation_ids' => null,
        'restricted_department_ids' => null,
        'restricted_group_ids' => null,
        'browser_allowed' => null,
        'terminal_allowed' => null,
        'app_allowed' => null,
        'free_fields' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'id' => true,
        'name' => false,
        'token' => true,
        'number' => true,
        'description' => true,
        'end_date' => true,
        'is_active' => false,
        'is_used' => false,
        'work_operation_ids' => false,
        'restricted_department_ids' => false,
        'restricted_group_ids' => false,
        'browser_allowed' => false,
        'terminal_allowed' => false,
        'app_allowed' => false,
        'free_fields' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'token' => 'token',
        'number' => 'number',
        'description' => 'description',
        'end_date' => 'endDate',
        'is_active' => 'isActive',
        'is_used' => 'isUsed',
        'work_operation_ids' => 'workOperationIds',
        'restricted_department_ids' => 'restrictedDepartmentIds',
        'restricted_group_ids' => 'restrictedGroupIds',
        'browser_allowed' => 'browserAllowed',
        'terminal_allowed' => 'terminalAllowed',
        'app_allowed' => 'appAllowed',
        'free_fields' => 'freeFields'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'token' => 'setToken',
        'number' => 'setNumber',
        'description' => 'setDescription',
        'end_date' => 'setEndDate',
        'is_active' => 'setIsActive',
        'is_used' => 'setIsUsed',
        'work_operation_ids' => 'setWorkOperationIds',
        'restricted_department_ids' => 'setRestrictedDepartmentIds',
        'restricted_group_ids' => 'setRestrictedGroupIds',
        'browser_allowed' => 'setBrowserAllowed',
        'terminal_allowed' => 'setTerminalAllowed',
        'app_allowed' => 'setAppAllowed',
        'free_fields' => 'setFreeFields'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'token' => 'getToken',
        'number' => 'getNumber',
        'description' => 'getDescription',
        'end_date' => 'getEndDate',
        'is_active' => 'getIsActive',
        'is_used' => 'getIsUsed',
        'work_operation_ids' => 'getWorkOperationIds',
        'restricted_department_ids' => 'getRestrictedDepartmentIds',
        'restricted_group_ids' => 'getRestrictedGroupIds',
        'browser_allowed' => 'getBrowserAllowed',
        'terminal_allowed' => 'getTerminalAllowed',
        'app_allowed' => 'getAppAllowed',
        'free_fields' => 'getFreeFields'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('token', $data ?? [], null);
        $this->setIfExists('number', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('end_date', $data ?? [], null);
        $this->setIfExists('is_active', $data ?? [], null);
        $this->setIfExists('is_used', $data ?? [], null);
        $this->setIfExists('work_operation_ids', $data ?? [], null);
        $this->setIfExists('restricted_department_ids', $data ?? [], null);
        $this->setIfExists('restricted_group_ids', $data ?? [], null);
        $this->setIfExists('browser_allowed', $data ?? [], null);
        $this->setIfExists('terminal_allowed', $data ?? [], null);
        $this->setIfExists('app_allowed', $data ?? [], null);
        $this->setIfExists('free_fields', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if (($this->container['id'] > 9007199254740991)) {
            $invalidProperties[] = "invalid value for 'id', must be smaller than or equal to 9007199254740991.";
        }

        if (($this->container['id'] < -9007199254740991)) {
            $invalidProperties[] = "invalid value for 'id', must be bigger than or equal to -9007199254740991.";
        }

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['token'] === null) {
            $invalidProperties[] = "'token' can't be null";
        }
        if ($this->container['number'] === null) {
            $invalidProperties[] = "'number' can't be null";
        }
        if (($this->container['number'] > 9007199254740991)) {
            $invalidProperties[] = "invalid value for 'number', must be smaller than or equal to 9007199254740991.";
        }

        if (($this->container['number'] < -9007199254740991)) {
            $invalidProperties[] = "invalid value for 'number', must be bigger than or equal to -9007199254740991.";
        }

        if ($this->container['description'] === null) {
            $invalidProperties[] = "'description' can't be null";
        }
        if ($this->container['end_date'] === null) {
            $invalidProperties[] = "'end_date' can't be null";
        }
        if ($this->container['is_active'] === null) {
            $invalidProperties[] = "'is_active' can't be null";
        }
        if ($this->container['is_used'] === null) {
            $invalidProperties[] = "'is_used' can't be null";
        }
        if ($this->container['work_operation_ids'] === null) {
            $invalidProperties[] = "'work_operation_ids' can't be null";
        }
        if ($this->container['restricted_department_ids'] === null) {
            $invalidProperties[] = "'restricted_department_ids' can't be null";
        }
        if ($this->container['restricted_group_ids'] === null) {
            $invalidProperties[] = "'restricted_group_ids' can't be null";
        }
        if ($this->container['browser_allowed'] === null) {
            $invalidProperties[] = "'browser_allowed' can't be null";
        }
        if ($this->container['terminal_allowed'] === null) {
            $invalidProperties[] = "'terminal_allowed' can't be null";
        }
        if ($this->container['app_allowed'] === null) {
            $invalidProperties[] = "'app_allowed' can't be null";
        }
        if ($this->container['free_fields'] === null) {
            $invalidProperties[] = "'free_fields' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId(): ?int
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return $this
     */
    public function setId(?int $id): static
    {
        if (is_null($id)) {
            array_push($this->openAPINullablesSetToNull, 'id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($id) && ($id > 9007199254740991)) {
            throw new InvalidArgumentException('invalid value for $id when calling CreateProject201Response., must be smaller than or equal to 9007199254740991.');
        }
        if (!is_null($id) && ($id < -9007199254740991)) {
            throw new InvalidArgumentException('invalid value for $id when calling CreateProject201Response., must be bigger than or equal to -9007199254740991.');
        }

        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName(): string
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName(string $name): static
    {
        if (is_null($name)) {
            throw new InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets token
     *
     * @return string
     */
    public function getToken(): ?string
    {
        return $this->container['token'];
    }

    /**
     * Sets token
     *
     * @param string $token token
     *
     * @return $this
     */
    public function setToken(?string $token): static
    {
        if (is_null($token)) {
            array_push($this->openAPINullablesSetToNull, 'token');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('token', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['token'] = $token;

        return $this;
    }

    /**
     * Gets number
     *
     * @return int
     */
    public function getNumber(): ?int
    {
        return $this->container['number'];
    }

    /**
     * Sets number
     *
     * @param int $number number
     *
     * @return $this
     */
    public function setNumber(?int $number): static
    {
        if (is_null($number)) {
            array_push($this->openAPINullablesSetToNull, 'number');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('number', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($number) && ($number > 9007199254740991)) {
            throw new InvalidArgumentException('invalid value for $number when calling CreateProject201Response., must be smaller than or equal to 9007199254740991.');
        }
        if (!is_null($number) && ($number < -9007199254740991)) {
            throw new InvalidArgumentException('invalid value for $number when calling CreateProject201Response., must be bigger than or equal to -9007199254740991.');
        }

        $this->container['number'] = $number;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription(): ?string
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description description
     *
     * @return $this
     */
    public function setDescription(?string $description): static
    {
        if (is_null($description)) {
            array_push($this->openAPINullablesSetToNull, 'description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets end_date
     *
     * @return string
     */
    public function getEndDate(): ?string
    {
        return $this->container['end_date'];
    }

    /**
     * Sets end_date
     *
     * @param string $end_date end_date
     *
     * @return $this
     */
    public function setEndDate(?string $end_date): static
    {
        if (is_null($end_date)) {
            array_push($this->openAPINullablesSetToNull, 'end_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('end_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['end_date'] = $end_date;

        return $this;
    }

    /**
     * Gets is_active
     *
     * @return bool
     */
    public function getIsActive(): bool
    {
        return $this->container['is_active'];
    }

    /**
     * Sets is_active
     *
     * @param bool $is_active is_active
     *
     * @return $this
     */
    public function setIsActive(bool $is_active): static
    {
        if (is_null($is_active)) {
            throw new InvalidArgumentException('non-nullable is_active cannot be null');
        }
        $this->container['is_active'] = $is_active;

        return $this;
    }

    /**
     * Gets is_used
     *
     * @return bool
     */
    public function getIsUsed(): bool
    {
        return $this->container['is_used'];
    }

    /**
     * Sets is_used
     *
     * @param bool $is_used is_used
     *
     * @return $this
     */
    public function setIsUsed(bool $is_used): static
    {
        if (is_null($is_used)) {
            throw new InvalidArgumentException('non-nullable is_used cannot be null');
        }
        $this->container['is_used'] = $is_used;

        return $this;
    }

    /**
     * Gets work_operation_ids
     *
     * @return int[]
     */
    public function getWorkOperationIds(): array
    {
        return $this->container['work_operation_ids'];
    }

    /**
     * Sets work_operation_ids
     *
     * @param int[] $work_operation_ids work_operation_ids
     *
     * @return $this
     */
    public function setWorkOperationIds(array $work_operation_ids): static
    {
        if (is_null($work_operation_ids)) {
            throw new InvalidArgumentException('non-nullable work_operation_ids cannot be null');
        }
        $this->container['work_operation_ids'] = $work_operation_ids;

        return $this;
    }

    /**
     * Gets restricted_department_ids
     *
     * @return int[]
     */
    public function getRestrictedDepartmentIds(): array
    {
        return $this->container['restricted_department_ids'];
    }

    /**
     * Sets restricted_department_ids
     *
     * @param int[] $restricted_department_ids restricted_department_ids
     *
     * @return $this
     */
    public function setRestrictedDepartmentIds(array $restricted_department_ids): static
    {
        if (is_null($restricted_department_ids)) {
            throw new InvalidArgumentException('non-nullable restricted_department_ids cannot be null');
        }
        $this->container['restricted_department_ids'] = $restricted_department_ids;

        return $this;
    }

    /**
     * Gets restricted_group_ids
     *
     * @return int[]
     */
    public function getRestrictedGroupIds(): array
    {
        return $this->container['restricted_group_ids'];
    }

    /**
     * Sets restricted_group_ids
     *
     * @param int[] $restricted_group_ids restricted_group_ids
     *
     * @return $this
     */
    public function setRestrictedGroupIds(array $restricted_group_ids): static
    {
        if (is_null($restricted_group_ids)) {
            throw new InvalidArgumentException('non-nullable restricted_group_ids cannot be null');
        }
        $this->container['restricted_group_ids'] = $restricted_group_ids;

        return $this;
    }

    /**
     * Gets browser_allowed
     *
     * @return bool
     */
    public function getBrowserAllowed(): bool
    {
        return $this->container['browser_allowed'];
    }

    /**
     * Sets browser_allowed
     *
     * @param bool $browser_allowed browser_allowed
     *
     * @return $this
     */
    public function setBrowserAllowed(bool $browser_allowed): static
    {
        if (is_null($browser_allowed)) {
            throw new InvalidArgumentException('non-nullable browser_allowed cannot be null');
        }
        $this->container['browser_allowed'] = $browser_allowed;

        return $this;
    }

    /**
     * Gets terminal_allowed
     *
     * @return bool
     */
    public function getTerminalAllowed(): bool
    {
        return $this->container['terminal_allowed'];
    }

    /**
     * Sets terminal_allowed
     *
     * @param bool $terminal_allowed terminal_allowed
     *
     * @return $this
     */
    public function setTerminalAllowed(bool $terminal_allowed): static
    {
        if (is_null($terminal_allowed)) {
            throw new InvalidArgumentException('non-nullable terminal_allowed cannot be null');
        }
        $this->container['terminal_allowed'] = $terminal_allowed;

        return $this;
    }

    /**
     * Gets app_allowed
     *
     * @return bool
     */
    public function getAppAllowed(): bool
    {
        return $this->container['app_allowed'];
    }

    /**
     * Sets app_allowed
     *
     * @param bool $app_allowed app_allowed
     *
     * @return $this
     */
    public function setAppAllowed(bool $app_allowed): static
    {
        if (is_null($app_allowed)) {
            throw new InvalidArgumentException('non-nullable app_allowed cannot be null');
        }
        $this->container['app_allowed'] = $app_allowed;

        return $this;
    }

    /**
     * Gets free_fields
     *
     * @return \TimecardClient\Model\CreatePerson201ResponseFreeFieldsInner[]
     */
    public function getFreeFields(): array
    {
        return $this->container['free_fields'];
    }

    /**
     * Sets free_fields
     *
     * @param \TimecardClient\Model\CreatePerson201ResponseFreeFieldsInner[] $free_fields free_fields
     *
     * @return $this
     */
    public function setFreeFields(array $free_fields): static
    {
        if (is_null($free_fields)) {
            throw new InvalidArgumentException('non-nullable free_fields cannot be null');
        }
        $this->container['free_fields'] = $free_fields;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


