<?php
/**
 * GetAbsenceType200Response
 *
 * PHP version 8.1
 *
 * @package  TimecardClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * timeCard REST facade
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TimecardClient\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use TimecardClient\ObjectSerializer;

/**
 * GetAbsenceType200Response Class Doc Comment
 *
 * @package  TimecardClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class GetAbsenceType200Response implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'getAbsenceType_200_response';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'id' => 'int',
        'order_no' => 'int',
        'name' => 'string',
        'token' => 'string',
        'is_holiday' => 'bool',
        'color' => 'string',
        'has_replace_time' => 'bool',
        'weighting_type' => 'int',
        'alt_name' => 'string',
        'alt_color' => 'string',
        'description' => 'string',
        'is_working_time' => 'bool',
        'only_core_time' => 'bool',
        'allowed_for_requests' => 'bool',
        'allowed_for_bookings_with_reason' => 'bool',
        'allowed_for_manual_full_day' => 'bool',
        'allowed_for_self' => 'bool',
        'use_pause_rule' => 'bool',
        'replace_time_state' => 'string',
        'replace_time' => 'string',
        'analysis_rounding' => 'bool',
        'analysis_project' => 'bool',
        'rounding_last_go' => 'bool',
        'is_used' => 'bool',
        'is_system' => 'bool',
        'restricted_department_ids' => 'int[]',
        'restricted_group_ids' => 'int[]',
        'browser_allowed' => 'bool',
        'terminal_allowed' => 'bool',
        'app_allowed' => 'bool',
        'presence_allowed' => 'bool',
        'also_illness' => 'bool',
        'reduce_illness' => 'bool',
        'free_fields' => '\TimecardClient\Model\CreatePerson201ResponseFreeFieldsInner[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'id' => null,
        'order_no' => null,
        'name' => null,
        'token' => null,
        'is_holiday' => null,
        'color' => null,
        'has_replace_time' => null,
        'weighting_type' => null,
        'alt_name' => null,
        'alt_color' => null,
        'description' => null,
        'is_working_time' => null,
        'only_core_time' => null,
        'allowed_for_requests' => null,
        'allowed_for_bookings_with_reason' => null,
        'allowed_for_manual_full_day' => null,
        'allowed_for_self' => null,
        'use_pause_rule' => null,
        'replace_time_state' => null,
        'replace_time' => null,
        'analysis_rounding' => null,
        'analysis_project' => null,
        'rounding_last_go' => null,
        'is_used' => null,
        'is_system' => null,
        'restricted_department_ids' => null,
        'restricted_group_ids' => null,
        'browser_allowed' => null,
        'terminal_allowed' => null,
        'app_allowed' => null,
        'presence_allowed' => null,
        'also_illness' => null,
        'reduce_illness' => null,
        'free_fields' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'id' => true,
        'order_no' => true,
        'name' => false,
        'token' => true,
        'is_holiday' => false,
        'color' => true,
        'has_replace_time' => false,
        'weighting_type' => true,
        'alt_name' => true,
        'alt_color' => true,
        'description' => true,
        'is_working_time' => false,
        'only_core_time' => false,
        'allowed_for_requests' => false,
        'allowed_for_bookings_with_reason' => false,
        'allowed_for_manual_full_day' => false,
        'allowed_for_self' => true,
        'use_pause_rule' => false,
        'replace_time_state' => false,
        'replace_time' => true,
        'analysis_rounding' => false,
        'analysis_project' => false,
        'rounding_last_go' => false,
        'is_used' => false,
        'is_system' => false,
        'restricted_department_ids' => false,
        'restricted_group_ids' => false,
        'browser_allowed' => false,
        'terminal_allowed' => false,
        'app_allowed' => false,
        'presence_allowed' => false,
        'also_illness' => true,
        'reduce_illness' => true,
        'free_fields' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'id' => 'id',
        'order_no' => 'orderNo',
        'name' => 'name',
        'token' => 'token',
        'is_holiday' => 'isHoliday',
        'color' => 'color',
        'has_replace_time' => 'hasReplaceTime',
        'weighting_type' => 'weightingType',
        'alt_name' => 'altName',
        'alt_color' => 'altColor',
        'description' => 'description',
        'is_working_time' => 'isWorkingTime',
        'only_core_time' => 'onlyCoreTime',
        'allowed_for_requests' => 'allowedForRequests',
        'allowed_for_bookings_with_reason' => 'allowedForBookingsWithReason',
        'allowed_for_manual_full_day' => 'allowedForManualFullDay',
        'allowed_for_self' => 'allowedForSelf',
        'use_pause_rule' => 'usePauseRule',
        'replace_time_state' => 'replaceTimeState',
        'replace_time' => 'replaceTime',
        'analysis_rounding' => 'analysisRounding',
        'analysis_project' => 'analysisProject',
        'rounding_last_go' => 'roundingLastGo',
        'is_used' => 'isUsed',
        'is_system' => 'isSystem',
        'restricted_department_ids' => 'restrictedDepartmentIds',
        'restricted_group_ids' => 'restrictedGroupIds',
        'browser_allowed' => 'browserAllowed',
        'terminal_allowed' => 'terminalAllowed',
        'app_allowed' => 'appAllowed',
        'presence_allowed' => 'presenceAllowed',
        'also_illness' => 'alsoIllness',
        'reduce_illness' => 'reduceIllness',
        'free_fields' => 'freeFields'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'id' => 'setId',
        'order_no' => 'setOrderNo',
        'name' => 'setName',
        'token' => 'setToken',
        'is_holiday' => 'setIsHoliday',
        'color' => 'setColor',
        'has_replace_time' => 'setHasReplaceTime',
        'weighting_type' => 'setWeightingType',
        'alt_name' => 'setAltName',
        'alt_color' => 'setAltColor',
        'description' => 'setDescription',
        'is_working_time' => 'setIsWorkingTime',
        'only_core_time' => 'setOnlyCoreTime',
        'allowed_for_requests' => 'setAllowedForRequests',
        'allowed_for_bookings_with_reason' => 'setAllowedForBookingsWithReason',
        'allowed_for_manual_full_day' => 'setAllowedForManualFullDay',
        'allowed_for_self' => 'setAllowedForSelf',
        'use_pause_rule' => 'setUsePauseRule',
        'replace_time_state' => 'setReplaceTimeState',
        'replace_time' => 'setReplaceTime',
        'analysis_rounding' => 'setAnalysisRounding',
        'analysis_project' => 'setAnalysisProject',
        'rounding_last_go' => 'setRoundingLastGo',
        'is_used' => 'setIsUsed',
        'is_system' => 'setIsSystem',
        'restricted_department_ids' => 'setRestrictedDepartmentIds',
        'restricted_group_ids' => 'setRestrictedGroupIds',
        'browser_allowed' => 'setBrowserAllowed',
        'terminal_allowed' => 'setTerminalAllowed',
        'app_allowed' => 'setAppAllowed',
        'presence_allowed' => 'setPresenceAllowed',
        'also_illness' => 'setAlsoIllness',
        'reduce_illness' => 'setReduceIllness',
        'free_fields' => 'setFreeFields'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'id' => 'getId',
        'order_no' => 'getOrderNo',
        'name' => 'getName',
        'token' => 'getToken',
        'is_holiday' => 'getIsHoliday',
        'color' => 'getColor',
        'has_replace_time' => 'getHasReplaceTime',
        'weighting_type' => 'getWeightingType',
        'alt_name' => 'getAltName',
        'alt_color' => 'getAltColor',
        'description' => 'getDescription',
        'is_working_time' => 'getIsWorkingTime',
        'only_core_time' => 'getOnlyCoreTime',
        'allowed_for_requests' => 'getAllowedForRequests',
        'allowed_for_bookings_with_reason' => 'getAllowedForBookingsWithReason',
        'allowed_for_manual_full_day' => 'getAllowedForManualFullDay',
        'allowed_for_self' => 'getAllowedForSelf',
        'use_pause_rule' => 'getUsePauseRule',
        'replace_time_state' => 'getReplaceTimeState',
        'replace_time' => 'getReplaceTime',
        'analysis_rounding' => 'getAnalysisRounding',
        'analysis_project' => 'getAnalysisProject',
        'rounding_last_go' => 'getRoundingLastGo',
        'is_used' => 'getIsUsed',
        'is_system' => 'getIsSystem',
        'restricted_department_ids' => 'getRestrictedDepartmentIds',
        'restricted_group_ids' => 'getRestrictedGroupIds',
        'browser_allowed' => 'getBrowserAllowed',
        'terminal_allowed' => 'getTerminalAllowed',
        'app_allowed' => 'getAppAllowed',
        'presence_allowed' => 'getPresenceAllowed',
        'also_illness' => 'getAlsoIllness',
        'reduce_illness' => 'getReduceIllness',
        'free_fields' => 'getFreeFields'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('order_no', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('token', $data ?? [], null);
        $this->setIfExists('is_holiday', $data ?? [], null);
        $this->setIfExists('color', $data ?? [], null);
        $this->setIfExists('has_replace_time', $data ?? [], null);
        $this->setIfExists('weighting_type', $data ?? [], null);
        $this->setIfExists('alt_name', $data ?? [], null);
        $this->setIfExists('alt_color', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('is_working_time', $data ?? [], null);
        $this->setIfExists('only_core_time', $data ?? [], null);
        $this->setIfExists('allowed_for_requests', $data ?? [], null);
        $this->setIfExists('allowed_for_bookings_with_reason', $data ?? [], null);
        $this->setIfExists('allowed_for_manual_full_day', $data ?? [], null);
        $this->setIfExists('allowed_for_self', $data ?? [], null);
        $this->setIfExists('use_pause_rule', $data ?? [], null);
        $this->setIfExists('replace_time_state', $data ?? [], null);
        $this->setIfExists('replace_time', $data ?? [], null);
        $this->setIfExists('analysis_rounding', $data ?? [], null);
        $this->setIfExists('analysis_project', $data ?? [], null);
        $this->setIfExists('rounding_last_go', $data ?? [], null);
        $this->setIfExists('is_used', $data ?? [], null);
        $this->setIfExists('is_system', $data ?? [], null);
        $this->setIfExists('restricted_department_ids', $data ?? [], null);
        $this->setIfExists('restricted_group_ids', $data ?? [], null);
        $this->setIfExists('browser_allowed', $data ?? [], null);
        $this->setIfExists('terminal_allowed', $data ?? [], null);
        $this->setIfExists('app_allowed', $data ?? [], null);
        $this->setIfExists('presence_allowed', $data ?? [], null);
        $this->setIfExists('also_illness', $data ?? [], null);
        $this->setIfExists('reduce_illness', $data ?? [], null);
        $this->setIfExists('free_fields', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if (($this->container['id'] > 9007199254740991)) {
            $invalidProperties[] = "invalid value for 'id', must be smaller than or equal to 9007199254740991.";
        }

        if (($this->container['id'] < -9007199254740991)) {
            $invalidProperties[] = "invalid value for 'id', must be bigger than or equal to -9007199254740991.";
        }

        if ($this->container['order_no'] === null) {
            $invalidProperties[] = "'order_no' can't be null";
        }
        if (($this->container['order_no'] > 9007199254740991)) {
            $invalidProperties[] = "invalid value for 'order_no', must be smaller than or equal to 9007199254740991.";
        }

        if (($this->container['order_no'] < -9007199254740991)) {
            $invalidProperties[] = "invalid value for 'order_no', must be bigger than or equal to -9007199254740991.";
        }

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['token'] === null) {
            $invalidProperties[] = "'token' can't be null";
        }
        if ($this->container['is_holiday'] === null) {
            $invalidProperties[] = "'is_holiday' can't be null";
        }
        if ($this->container['color'] === null) {
            $invalidProperties[] = "'color' can't be null";
        }
        if ($this->container['has_replace_time'] === null) {
            $invalidProperties[] = "'has_replace_time' can't be null";
        }
        if ($this->container['weighting_type'] === null) {
            $invalidProperties[] = "'weighting_type' can't be null";
        }
        if (($this->container['weighting_type'] > 9007199254740991)) {
            $invalidProperties[] = "invalid value for 'weighting_type', must be smaller than or equal to 9007199254740991.";
        }

        if (($this->container['weighting_type'] < -9007199254740991)) {
            $invalidProperties[] = "invalid value for 'weighting_type', must be bigger than or equal to -9007199254740991.";
        }

        if ($this->container['alt_name'] === null) {
            $invalidProperties[] = "'alt_name' can't be null";
        }
        if ($this->container['alt_color'] === null) {
            $invalidProperties[] = "'alt_color' can't be null";
        }
        if ($this->container['description'] === null) {
            $invalidProperties[] = "'description' can't be null";
        }
        if ($this->container['is_working_time'] === null) {
            $invalidProperties[] = "'is_working_time' can't be null";
        }
        if ($this->container['only_core_time'] === null) {
            $invalidProperties[] = "'only_core_time' can't be null";
        }
        if ($this->container['allowed_for_requests'] === null) {
            $invalidProperties[] = "'allowed_for_requests' can't be null";
        }
        if ($this->container['allowed_for_bookings_with_reason'] === null) {
            $invalidProperties[] = "'allowed_for_bookings_with_reason' can't be null";
        }
        if ($this->container['allowed_for_manual_full_day'] === null) {
            $invalidProperties[] = "'allowed_for_manual_full_day' can't be null";
        }
        if ($this->container['allowed_for_self'] === null) {
            $invalidProperties[] = "'allowed_for_self' can't be null";
        }
        if ($this->container['use_pause_rule'] === null) {
            $invalidProperties[] = "'use_pause_rule' can't be null";
        }
        if ($this->container['replace_time_state'] === null) {
            $invalidProperties[] = "'replace_time_state' can't be null";
        }
        if ($this->container['replace_time'] === null) {
            $invalidProperties[] = "'replace_time' can't be null";
        }
        if ($this->container['analysis_rounding'] === null) {
            $invalidProperties[] = "'analysis_rounding' can't be null";
        }
        if ($this->container['analysis_project'] === null) {
            $invalidProperties[] = "'analysis_project' can't be null";
        }
        if ($this->container['rounding_last_go'] === null) {
            $invalidProperties[] = "'rounding_last_go' can't be null";
        }
        if ($this->container['is_used'] === null) {
            $invalidProperties[] = "'is_used' can't be null";
        }
        if ($this->container['is_system'] === null) {
            $invalidProperties[] = "'is_system' can't be null";
        }
        if ($this->container['restricted_department_ids'] === null) {
            $invalidProperties[] = "'restricted_department_ids' can't be null";
        }
        if ($this->container['restricted_group_ids'] === null) {
            $invalidProperties[] = "'restricted_group_ids' can't be null";
        }
        if ($this->container['browser_allowed'] === null) {
            $invalidProperties[] = "'browser_allowed' can't be null";
        }
        if ($this->container['terminal_allowed'] === null) {
            $invalidProperties[] = "'terminal_allowed' can't be null";
        }
        if ($this->container['app_allowed'] === null) {
            $invalidProperties[] = "'app_allowed' can't be null";
        }
        if ($this->container['presence_allowed'] === null) {
            $invalidProperties[] = "'presence_allowed' can't be null";
        }
        if ($this->container['also_illness'] === null) {
            $invalidProperties[] = "'also_illness' can't be null";
        }
        if ($this->container['reduce_illness'] === null) {
            $invalidProperties[] = "'reduce_illness' can't be null";
        }
        if ($this->container['free_fields'] === null) {
            $invalidProperties[] = "'free_fields' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId(): ?int
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return $this
     */
    public function setId(?int $id): static
    {
        if (is_null($id)) {
            array_push($this->openAPINullablesSetToNull, 'id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($id) && ($id > 9007199254740991)) {
            throw new InvalidArgumentException('invalid value for $id when calling GetAbsenceType200Response., must be smaller than or equal to 9007199254740991.');
        }
        if (!is_null($id) && ($id < -9007199254740991)) {
            throw new InvalidArgumentException('invalid value for $id when calling GetAbsenceType200Response., must be bigger than or equal to -9007199254740991.');
        }

        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets order_no
     *
     * @return int
     */
    public function getOrderNo(): ?int
    {
        return $this->container['order_no'];
    }

    /**
     * Sets order_no
     *
     * @param int $order_no order_no
     *
     * @return $this
     */
    public function setOrderNo(?int $order_no): static
    {
        if (is_null($order_no)) {
            array_push($this->openAPINullablesSetToNull, 'order_no');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('order_no', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($order_no) && ($order_no > 9007199254740991)) {
            throw new InvalidArgumentException('invalid value for $order_no when calling GetAbsenceType200Response., must be smaller than or equal to 9007199254740991.');
        }
        if (!is_null($order_no) && ($order_no < -9007199254740991)) {
            throw new InvalidArgumentException('invalid value for $order_no when calling GetAbsenceType200Response., must be bigger than or equal to -9007199254740991.');
        }

        $this->container['order_no'] = $order_no;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName(): string
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName(string $name): static
    {
        if (is_null($name)) {
            throw new InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets token
     *
     * @return string
     */
    public function getToken(): ?string
    {
        return $this->container['token'];
    }

    /**
     * Sets token
     *
     * @param string $token token
     *
     * @return $this
     */
    public function setToken(?string $token): static
    {
        if (is_null($token)) {
            array_push($this->openAPINullablesSetToNull, 'token');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('token', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['token'] = $token;

        return $this;
    }

    /**
     * Gets is_holiday
     *
     * @return bool
     */
    public function getIsHoliday(): bool
    {
        return $this->container['is_holiday'];
    }

    /**
     * Sets is_holiday
     *
     * @param bool $is_holiday is_holiday
     *
     * @return $this
     */
    public function setIsHoliday(bool $is_holiday): static
    {
        if (is_null($is_holiday)) {
            throw new InvalidArgumentException('non-nullable is_holiday cannot be null');
        }
        $this->container['is_holiday'] = $is_holiday;

        return $this;
    }

    /**
     * Gets color
     *
     * @return string
     */
    public function getColor(): ?string
    {
        return $this->container['color'];
    }

    /**
     * Sets color
     *
     * @param string $color color
     *
     * @return $this
     */
    public function setColor(?string $color): static
    {
        if (is_null($color)) {
            array_push($this->openAPINullablesSetToNull, 'color');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('color', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['color'] = $color;

        return $this;
    }

    /**
     * Gets has_replace_time
     *
     * @return bool
     */
    public function getHasReplaceTime(): bool
    {
        return $this->container['has_replace_time'];
    }

    /**
     * Sets has_replace_time
     *
     * @param bool $has_replace_time has_replace_time
     *
     * @return $this
     */
    public function setHasReplaceTime(bool $has_replace_time): static
    {
        if (is_null($has_replace_time)) {
            throw new InvalidArgumentException('non-nullable has_replace_time cannot be null');
        }
        $this->container['has_replace_time'] = $has_replace_time;

        return $this;
    }

    /**
     * Gets weighting_type
     *
     * @return int
     */
    public function getWeightingType(): ?int
    {
        return $this->container['weighting_type'];
    }

    /**
     * Sets weighting_type
     *
     * @param int $weighting_type weighting_type
     *
     * @return $this
     */
    public function setWeightingType(?int $weighting_type): static
    {
        if (is_null($weighting_type)) {
            array_push($this->openAPINullablesSetToNull, 'weighting_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('weighting_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($weighting_type) && ($weighting_type > 9007199254740991)) {
            throw new InvalidArgumentException('invalid value for $weighting_type when calling GetAbsenceType200Response., must be smaller than or equal to 9007199254740991.');
        }
        if (!is_null($weighting_type) && ($weighting_type < -9007199254740991)) {
            throw new InvalidArgumentException('invalid value for $weighting_type when calling GetAbsenceType200Response., must be bigger than or equal to -9007199254740991.');
        }

        $this->container['weighting_type'] = $weighting_type;

        return $this;
    }

    /**
     * Gets alt_name
     *
     * @return string
     */
    public function getAltName(): ?string
    {
        return $this->container['alt_name'];
    }

    /**
     * Sets alt_name
     *
     * @param string $alt_name alt_name
     *
     * @return $this
     */
    public function setAltName(?string $alt_name): static
    {
        if (is_null($alt_name)) {
            array_push($this->openAPINullablesSetToNull, 'alt_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('alt_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['alt_name'] = $alt_name;

        return $this;
    }

    /**
     * Gets alt_color
     *
     * @return string
     */
    public function getAltColor(): ?string
    {
        return $this->container['alt_color'];
    }

    /**
     * Sets alt_color
     *
     * @param string $alt_color alt_color
     *
     * @return $this
     */
    public function setAltColor(?string $alt_color): static
    {
        if (is_null($alt_color)) {
            array_push($this->openAPINullablesSetToNull, 'alt_color');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('alt_color', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['alt_color'] = $alt_color;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription(): ?string
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description description
     *
     * @return $this
     */
    public function setDescription(?string $description): static
    {
        if (is_null($description)) {
            array_push($this->openAPINullablesSetToNull, 'description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets is_working_time
     *
     * @return bool
     */
    public function getIsWorkingTime(): bool
    {
        return $this->container['is_working_time'];
    }

    /**
     * Sets is_working_time
     *
     * @param bool $is_working_time is_working_time
     *
     * @return $this
     */
    public function setIsWorkingTime(bool $is_working_time): static
    {
        if (is_null($is_working_time)) {
            throw new InvalidArgumentException('non-nullable is_working_time cannot be null');
        }
        $this->container['is_working_time'] = $is_working_time;

        return $this;
    }

    /**
     * Gets only_core_time
     *
     * @return bool
     */
    public function getOnlyCoreTime(): bool
    {
        return $this->container['only_core_time'];
    }

    /**
     * Sets only_core_time
     *
     * @param bool $only_core_time only_core_time
     *
     * @return $this
     */
    public function setOnlyCoreTime(bool $only_core_time): static
    {
        if (is_null($only_core_time)) {
            throw new InvalidArgumentException('non-nullable only_core_time cannot be null');
        }
        $this->container['only_core_time'] = $only_core_time;

        return $this;
    }

    /**
     * Gets allowed_for_requests
     *
     * @return bool
     */
    public function getAllowedForRequests(): bool
    {
        return $this->container['allowed_for_requests'];
    }

    /**
     * Sets allowed_for_requests
     *
     * @param bool $allowed_for_requests allowed_for_requests
     *
     * @return $this
     */
    public function setAllowedForRequests(bool $allowed_for_requests): static
    {
        if (is_null($allowed_for_requests)) {
            throw new InvalidArgumentException('non-nullable allowed_for_requests cannot be null');
        }
        $this->container['allowed_for_requests'] = $allowed_for_requests;

        return $this;
    }

    /**
     * Gets allowed_for_bookings_with_reason
     *
     * @return bool
     */
    public function getAllowedForBookingsWithReason(): bool
    {
        return $this->container['allowed_for_bookings_with_reason'];
    }

    /**
     * Sets allowed_for_bookings_with_reason
     *
     * @param bool $allowed_for_bookings_with_reason allowed_for_bookings_with_reason
     *
     * @return $this
     */
    public function setAllowedForBookingsWithReason(bool $allowed_for_bookings_with_reason): static
    {
        if (is_null($allowed_for_bookings_with_reason)) {
            throw new InvalidArgumentException('non-nullable allowed_for_bookings_with_reason cannot be null');
        }
        $this->container['allowed_for_bookings_with_reason'] = $allowed_for_bookings_with_reason;

        return $this;
    }

    /**
     * Gets allowed_for_manual_full_day
     *
     * @return bool
     */
    public function getAllowedForManualFullDay(): bool
    {
        return $this->container['allowed_for_manual_full_day'];
    }

    /**
     * Sets allowed_for_manual_full_day
     *
     * @param bool $allowed_for_manual_full_day allowed_for_manual_full_day
     *
     * @return $this
     */
    public function setAllowedForManualFullDay(bool $allowed_for_manual_full_day): static
    {
        if (is_null($allowed_for_manual_full_day)) {
            throw new InvalidArgumentException('non-nullable allowed_for_manual_full_day cannot be null');
        }
        $this->container['allowed_for_manual_full_day'] = $allowed_for_manual_full_day;

        return $this;
    }

    /**
     * Gets allowed_for_self
     *
     * @return bool
     */
    public function getAllowedForSelf(): ?bool
    {
        return $this->container['allowed_for_self'];
    }

    /**
     * Sets allowed_for_self
     *
     * @param bool $allowed_for_self allowed_for_self
     *
     * @return $this
     */
    public function setAllowedForSelf(?bool $allowed_for_self): static
    {
        if (is_null($allowed_for_self)) {
            array_push($this->openAPINullablesSetToNull, 'allowed_for_self');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('allowed_for_self', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['allowed_for_self'] = $allowed_for_self;

        return $this;
    }

    /**
     * Gets use_pause_rule
     *
     * @return bool
     */
    public function getUsePauseRule(): bool
    {
        return $this->container['use_pause_rule'];
    }

    /**
     * Sets use_pause_rule
     *
     * @param bool $use_pause_rule use_pause_rule
     *
     * @return $this
     */
    public function setUsePauseRule(bool $use_pause_rule): static
    {
        if (is_null($use_pause_rule)) {
            throw new InvalidArgumentException('non-nullable use_pause_rule cannot be null');
        }
        $this->container['use_pause_rule'] = $use_pause_rule;

        return $this;
    }

    /**
     * Gets replace_time_state
     *
     * @return string
     */
    public function getReplaceTimeState(): string
    {
        return $this->container['replace_time_state'];
    }

    /**
     * Sets replace_time_state
     *
     * @param string $replace_time_state replace_time_state
     *
     * @return $this
     */
    public function setReplaceTimeState(string $replace_time_state): static
    {
        if (is_null($replace_time_state)) {
            throw new InvalidArgumentException('non-nullable replace_time_state cannot be null');
        }
        $this->container['replace_time_state'] = $replace_time_state;

        return $this;
    }

    /**
     * Gets replace_time
     *
     * @return string
     */
    public function getReplaceTime(): ?string
    {
        return $this->container['replace_time'];
    }

    /**
     * Sets replace_time
     *
     * @param string $replace_time replace_time
     *
     * @return $this
     */
    public function setReplaceTime(?string $replace_time): static
    {
        if (is_null($replace_time)) {
            array_push($this->openAPINullablesSetToNull, 'replace_time');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('replace_time', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['replace_time'] = $replace_time;

        return $this;
    }

    /**
     * Gets analysis_rounding
     *
     * @return bool
     */
    public function getAnalysisRounding(): bool
    {
        return $this->container['analysis_rounding'];
    }

    /**
     * Sets analysis_rounding
     *
     * @param bool $analysis_rounding analysis_rounding
     *
     * @return $this
     */
    public function setAnalysisRounding(bool $analysis_rounding): static
    {
        if (is_null($analysis_rounding)) {
            throw new InvalidArgumentException('non-nullable analysis_rounding cannot be null');
        }
        $this->container['analysis_rounding'] = $analysis_rounding;

        return $this;
    }

    /**
     * Gets analysis_project
     *
     * @return bool
     */
    public function getAnalysisProject(): bool
    {
        return $this->container['analysis_project'];
    }

    /**
     * Sets analysis_project
     *
     * @param bool $analysis_project analysis_project
     *
     * @return $this
     */
    public function setAnalysisProject(bool $analysis_project): static
    {
        if (is_null($analysis_project)) {
            throw new InvalidArgumentException('non-nullable analysis_project cannot be null');
        }
        $this->container['analysis_project'] = $analysis_project;

        return $this;
    }

    /**
     * Gets rounding_last_go
     *
     * @return bool
     */
    public function getRoundingLastGo(): bool
    {
        return $this->container['rounding_last_go'];
    }

    /**
     * Sets rounding_last_go
     *
     * @param bool $rounding_last_go rounding_last_go
     *
     * @return $this
     */
    public function setRoundingLastGo(bool $rounding_last_go): static
    {
        if (is_null($rounding_last_go)) {
            throw new InvalidArgumentException('non-nullable rounding_last_go cannot be null');
        }
        $this->container['rounding_last_go'] = $rounding_last_go;

        return $this;
    }

    /**
     * Gets is_used
     *
     * @return bool
     */
    public function getIsUsed(): bool
    {
        return $this->container['is_used'];
    }

    /**
     * Sets is_used
     *
     * @param bool $is_used is_used
     *
     * @return $this
     */
    public function setIsUsed(bool $is_used): static
    {
        if (is_null($is_used)) {
            throw new InvalidArgumentException('non-nullable is_used cannot be null');
        }
        $this->container['is_used'] = $is_used;

        return $this;
    }

    /**
     * Gets is_system
     *
     * @return bool
     */
    public function getIsSystem(): bool
    {
        return $this->container['is_system'];
    }

    /**
     * Sets is_system
     *
     * @param bool $is_system is_system
     *
     * @return $this
     */
    public function setIsSystem(bool $is_system): static
    {
        if (is_null($is_system)) {
            throw new InvalidArgumentException('non-nullable is_system cannot be null');
        }
        $this->container['is_system'] = $is_system;

        return $this;
    }

    /**
     * Gets restricted_department_ids
     *
     * @return int[]
     */
    public function getRestrictedDepartmentIds(): array
    {
        return $this->container['restricted_department_ids'];
    }

    /**
     * Sets restricted_department_ids
     *
     * @param int[] $restricted_department_ids restricted_department_ids
     *
     * @return $this
     */
    public function setRestrictedDepartmentIds(array $restricted_department_ids): static
    {
        if (is_null($restricted_department_ids)) {
            throw new InvalidArgumentException('non-nullable restricted_department_ids cannot be null');
        }
        $this->container['restricted_department_ids'] = $restricted_department_ids;

        return $this;
    }

    /**
     * Gets restricted_group_ids
     *
     * @return int[]
     */
    public function getRestrictedGroupIds(): array
    {
        return $this->container['restricted_group_ids'];
    }

    /**
     * Sets restricted_group_ids
     *
     * @param int[] $restricted_group_ids restricted_group_ids
     *
     * @return $this
     */
    public function setRestrictedGroupIds(array $restricted_group_ids): static
    {
        if (is_null($restricted_group_ids)) {
            throw new InvalidArgumentException('non-nullable restricted_group_ids cannot be null');
        }
        $this->container['restricted_group_ids'] = $restricted_group_ids;

        return $this;
    }

    /**
     * Gets browser_allowed
     *
     * @return bool
     */
    public function getBrowserAllowed(): bool
    {
        return $this->container['browser_allowed'];
    }

    /**
     * Sets browser_allowed
     *
     * @param bool $browser_allowed browser_allowed
     *
     * @return $this
     */
    public function setBrowserAllowed(bool $browser_allowed): static
    {
        if (is_null($browser_allowed)) {
            throw new InvalidArgumentException('non-nullable browser_allowed cannot be null');
        }
        $this->container['browser_allowed'] = $browser_allowed;

        return $this;
    }

    /**
     * Gets terminal_allowed
     *
     * @return bool
     */
    public function getTerminalAllowed(): bool
    {
        return $this->container['terminal_allowed'];
    }

    /**
     * Sets terminal_allowed
     *
     * @param bool $terminal_allowed terminal_allowed
     *
     * @return $this
     */
    public function setTerminalAllowed(bool $terminal_allowed): static
    {
        if (is_null($terminal_allowed)) {
            throw new InvalidArgumentException('non-nullable terminal_allowed cannot be null');
        }
        $this->container['terminal_allowed'] = $terminal_allowed;

        return $this;
    }

    /**
     * Gets app_allowed
     *
     * @return bool
     */
    public function getAppAllowed(): bool
    {
        return $this->container['app_allowed'];
    }

    /**
     * Sets app_allowed
     *
     * @param bool $app_allowed app_allowed
     *
     * @return $this
     */
    public function setAppAllowed(bool $app_allowed): static
    {
        if (is_null($app_allowed)) {
            throw new InvalidArgumentException('non-nullable app_allowed cannot be null');
        }
        $this->container['app_allowed'] = $app_allowed;

        return $this;
    }

    /**
     * Gets presence_allowed
     *
     * @return bool
     */
    public function getPresenceAllowed(): bool
    {
        return $this->container['presence_allowed'];
    }

    /**
     * Sets presence_allowed
     *
     * @param bool $presence_allowed presence_allowed
     *
     * @return $this
     */
    public function setPresenceAllowed(bool $presence_allowed): static
    {
        if (is_null($presence_allowed)) {
            throw new InvalidArgumentException('non-nullable presence_allowed cannot be null');
        }
        $this->container['presence_allowed'] = $presence_allowed;

        return $this;
    }

    /**
     * Gets also_illness
     *
     * @return bool
     */
    public function getAlsoIllness(): ?bool
    {
        return $this->container['also_illness'];
    }

    /**
     * Sets also_illness
     *
     * @param bool $also_illness also_illness
     *
     * @return $this
     */
    public function setAlsoIllness(?bool $also_illness): static
    {
        if (is_null($also_illness)) {
            array_push($this->openAPINullablesSetToNull, 'also_illness');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('also_illness', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['also_illness'] = $also_illness;

        return $this;
    }

    /**
     * Gets reduce_illness
     *
     * @return bool
     */
    public function getReduceIllness(): ?bool
    {
        return $this->container['reduce_illness'];
    }

    /**
     * Sets reduce_illness
     *
     * @param bool $reduce_illness reduce_illness
     *
     * @return $this
     */
    public function setReduceIllness(?bool $reduce_illness): static
    {
        if (is_null($reduce_illness)) {
            array_push($this->openAPINullablesSetToNull, 'reduce_illness');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('reduce_illness', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['reduce_illness'] = $reduce_illness;

        return $this;
    }

    /**
     * Gets free_fields
     *
     * @return \TimecardClient\Model\CreatePerson201ResponseFreeFieldsInner[]
     */
    public function getFreeFields(): array
    {
        return $this->container['free_fields'];
    }

    /**
     * Sets free_fields
     *
     * @param \TimecardClient\Model\CreatePerson201ResponseFreeFieldsInner[] $free_fields free_fields
     *
     * @return $this
     */
    public function setFreeFields(array $free_fields): static
    {
        if (is_null($free_fields)) {
            throw new InvalidArgumentException('non-nullable free_fields cannot be null');
        }
        $this->container['free_fields'] = $free_fields;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


