<?php
/**
 * GetBreakRule200Response
 *
 * PHP version 8.1
 *
 * @package  TimecardClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * timeCard REST facade
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TimecardClient\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use TimecardClient\ObjectSerializer;

/**
 * GetBreakRule200Response Class Doc Comment
 *
 * @package  TimecardClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class GetBreakRule200Response implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'getBreakRule_200_response';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'id' => 'int',
        'name' => 'string',
        'type' => 'string',
        'description' => 'string',
        'durationMinutes' => 'int',
        'firstTime' => 'string',
        'secondTime' => 'string',
        'createAtBegin' => 'bool',
        'withBreathingTime' => 'bool',
        'completePresent' => 'bool',
        'isUsed' => 'bool',
        'isActive' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'id' => null,
        'name' => null,
        'type' => null,
        'description' => null,
        'durationMinutes' => null,
        'firstTime' => null,
        'secondTime' => null,
        'createAtBegin' => null,
        'withBreathingTime' => null,
        'completePresent' => null,
        'isUsed' => null,
        'isActive' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'id' => true,
        'name' => false,
        'type' => false,
        'description' => true,
        'durationMinutes' => true,
        'firstTime' => true,
        'secondTime' => true,
        'createAtBegin' => false,
        'withBreathingTime' => false,
        'completePresent' => true,
        'isUsed' => false,
        'isActive' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'type' => 'type',
        'description' => 'description',
        'durationMinutes' => 'durationMinutes',
        'firstTime' => 'firstTime',
        'secondTime' => 'secondTime',
        'createAtBegin' => 'createAtBegin',
        'withBreathingTime' => 'withBreathingTime',
        'completePresent' => 'completePresent',
        'isUsed' => 'isUsed',
        'isActive' => 'isActive'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'type' => 'setType',
        'description' => 'setDescription',
        'durationMinutes' => 'setDurationMinutes',
        'firstTime' => 'setFirstTime',
        'secondTime' => 'setSecondTime',
        'createAtBegin' => 'setCreateAtBegin',
        'withBreathingTime' => 'setWithBreathingTime',
        'completePresent' => 'setCompletePresent',
        'isUsed' => 'setIsUsed',
        'isActive' => 'setIsActive'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'type' => 'getType',
        'description' => 'getDescription',
        'durationMinutes' => 'getDurationMinutes',
        'firstTime' => 'getFirstTime',
        'secondTime' => 'getSecondTime',
        'createAtBegin' => 'getCreateAtBegin',
        'withBreathingTime' => 'getWithBreathingTime',
        'completePresent' => 'getCompletePresent',
        'isUsed' => 'getIsUsed',
        'isActive' => 'getIsActive'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('durationMinutes', $data ?? [], null);
        $this->setIfExists('firstTime', $data ?? [], null);
        $this->setIfExists('secondTime', $data ?? [], null);
        $this->setIfExists('createAtBegin', $data ?? [], null);
        $this->setIfExists('withBreathingTime', $data ?? [], null);
        $this->setIfExists('completePresent', $data ?? [], null);
        $this->setIfExists('isUsed', $data ?? [], null);
        $this->setIfExists('isActive', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if (($this->container['id'] > 9007199254740991)) {
            $invalidProperties[] = "invalid value for 'id', must be smaller than or equal to 9007199254740991.";
        }

        if (($this->container['id'] < -9007199254740991)) {
            $invalidProperties[] = "invalid value for 'id', must be bigger than or equal to -9007199254740991.";
        }

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        if ($this->container['description'] === null) {
            $invalidProperties[] = "'description' can't be null";
        }
        if ($this->container['durationMinutes'] === null) {
            $invalidProperties[] = "'durationMinutes' can't be null";
        }
        if (($this->container['durationMinutes'] > 9007199254740991)) {
            $invalidProperties[] = "invalid value for 'durationMinutes', must be smaller than or equal to 9007199254740991.";
        }

        if (($this->container['durationMinutes'] < -9007199254740991)) {
            $invalidProperties[] = "invalid value for 'durationMinutes', must be bigger than or equal to -9007199254740991.";
        }

        if ($this->container['firstTime'] === null) {
            $invalidProperties[] = "'firstTime' can't be null";
        }
        if ($this->container['secondTime'] === null) {
            $invalidProperties[] = "'secondTime' can't be null";
        }
        if ($this->container['createAtBegin'] === null) {
            $invalidProperties[] = "'createAtBegin' can't be null";
        }
        if ($this->container['withBreathingTime'] === null) {
            $invalidProperties[] = "'withBreathingTime' can't be null";
        }
        if ($this->container['completePresent'] === null) {
            $invalidProperties[] = "'completePresent' can't be null";
        }
        if ($this->container['isUsed'] === null) {
            $invalidProperties[] = "'isUsed' can't be null";
        }
        if ($this->container['isActive'] === null) {
            $invalidProperties[] = "'isActive' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId(): ?int
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return $this
     */
    public function setId(?int $id): static
    {
        if (is_null($id)) {
            array_push($this->openAPINullablesSetToNull, 'id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($id) && ($id > 9007199254740991)) {
            throw new InvalidArgumentException('invalid value for $id when calling GetBreakRule200Response., must be smaller than or equal to 9007199254740991.');
        }
        if (!is_null($id) && ($id < -9007199254740991)) {
            throw new InvalidArgumentException('invalid value for $id when calling GetBreakRule200Response., must be bigger than or equal to -9007199254740991.');
        }

        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName(): string
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName(string $name): static
    {
        if (is_null($name)) {
            throw new InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType(): string
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return $this
     */
    public function setType(string $type): static
    {
        if (is_null($type)) {
            throw new InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription(): ?string
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description description
     *
     * @return $this
     */
    public function setDescription(?string $description): static
    {
        if (is_null($description)) {
            array_push($this->openAPINullablesSetToNull, 'description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets durationMinutes
     *
     * @return int
     */
    public function getDurationMinutes(): ?int
    {
        return $this->container['durationMinutes'];
    }

    /**
     * Sets durationMinutes
     *
     * @param int $durationMinutes durationMinutes
     *
     * @return $this
     */
    public function setDurationMinutes(?int $durationMinutes): static
    {
        if (is_null($durationMinutes)) {
            array_push($this->openAPINullablesSetToNull, 'durationMinutes');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('durationMinutes', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($durationMinutes) && ($durationMinutes > 9007199254740991)) {
            throw new InvalidArgumentException('invalid value for $durationMinutes when calling GetBreakRule200Response., must be smaller than or equal to 9007199254740991.');
        }
        if (!is_null($durationMinutes) && ($durationMinutes < -9007199254740991)) {
            throw new InvalidArgumentException('invalid value for $durationMinutes when calling GetBreakRule200Response., must be bigger than or equal to -9007199254740991.');
        }

        $this->container['durationMinutes'] = $durationMinutes;

        return $this;
    }

    /**
     * Gets firstTime
     *
     * @return string
     */
    public function getFirstTime(): ?string
    {
        return $this->container['firstTime'];
    }

    /**
     * Sets firstTime
     *
     * @param string $firstTime firstTime
     *
     * @return $this
     */
    public function setFirstTime(?string $firstTime): static
    {
        if (is_null($firstTime)) {
            array_push($this->openAPINullablesSetToNull, 'firstTime');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('firstTime', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['firstTime'] = $firstTime;

        return $this;
    }

    /**
     * Gets secondTime
     *
     * @return string
     */
    public function getSecondTime(): ?string
    {
        return $this->container['secondTime'];
    }

    /**
     * Sets secondTime
     *
     * @param string $secondTime secondTime
     *
     * @return $this
     */
    public function setSecondTime(?string $secondTime): static
    {
        if (is_null($secondTime)) {
            array_push($this->openAPINullablesSetToNull, 'secondTime');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('secondTime', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['secondTime'] = $secondTime;

        return $this;
    }

    /**
     * Gets createAtBegin
     *
     * @return bool
     */
    public function getCreateAtBegin(): bool
    {
        return $this->container['createAtBegin'];
    }

    /**
     * Sets createAtBegin
     *
     * @param bool $createAtBegin createAtBegin
     *
     * @return $this
     */
    public function setCreateAtBegin(bool $createAtBegin): static
    {
        if (is_null($createAtBegin)) {
            throw new InvalidArgumentException('non-nullable createAtBegin cannot be null');
        }
        $this->container['createAtBegin'] = $createAtBegin;

        return $this;
    }

    /**
     * Gets withBreathingTime
     *
     * @return bool
     */
    public function getWithBreathingTime(): bool
    {
        return $this->container['withBreathingTime'];
    }

    /**
     * Sets withBreathingTime
     *
     * @param bool $withBreathingTime withBreathingTime
     *
     * @return $this
     */
    public function setWithBreathingTime(bool $withBreathingTime): static
    {
        if (is_null($withBreathingTime)) {
            throw new InvalidArgumentException('non-nullable withBreathingTime cannot be null');
        }
        $this->container['withBreathingTime'] = $withBreathingTime;

        return $this;
    }

    /**
     * Gets completePresent
     *
     * @return bool
     */
    public function getCompletePresent(): ?bool
    {
        return $this->container['completePresent'];
    }

    /**
     * Sets completePresent
     *
     * @param bool $completePresent completePresent
     *
     * @return $this
     */
    public function setCompletePresent(?bool $completePresent): static
    {
        if (is_null($completePresent)) {
            array_push($this->openAPINullablesSetToNull, 'completePresent');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('completePresent', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['completePresent'] = $completePresent;

        return $this;
    }

    /**
     * Gets isUsed
     *
     * @return bool
     */
    public function getIsUsed(): bool
    {
        return $this->container['isUsed'];
    }

    /**
     * Sets isUsed
     *
     * @param bool $isUsed isUsed
     *
     * @return $this
     */
    public function setIsUsed(bool $isUsed): static
    {
        if (is_null($isUsed)) {
            throw new InvalidArgumentException('non-nullable isUsed cannot be null');
        }
        $this->container['isUsed'] = $isUsed;

        return $this;
    }

    /**
     * Gets isActive
     *
     * @return bool
     */
    public function getIsActive(): bool
    {
        return $this->container['isActive'];
    }

    /**
     * Sets isActive
     *
     * @param bool $isActive isActive
     *
     * @return $this
     */
    public function setIsActive(bool $isActive): static
    {
        if (is_null($isActive)) {
            throw new InvalidArgumentException('non-nullable isActive cannot be null');
        }
        $this->container['isActive'] = $isActive;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


