<?php
/**
 * GetDailyBalance200ResponseCalculationsInner
 *
 * PHP version 8.1
 *
 * @package  TimecardClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * timeCard REST facade
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TimecardClient\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use TimecardClient\ObjectSerializer;

/**
 * GetDailyBalance200ResponseCalculationsInner Class Doc Comment
 *
 * @package  TimecardClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class GetDailyBalance200ResponseCalculationsInner implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'getDailyBalance_200_response_calculations_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'calculation_id' => 'int',
        'name' => 'string',
        'period' => 'string',
        'unit' => 'string',
        'is_holiday' => 'bool',
        'absence_name' => 'string',
        'range_from' => 'string',
        'range_to' => 'string',
        'range_text' => 'string',
        'start_value' => 'float',
        'target_value' => 'float',
        'total_value' => 'float',
        'carry_over' => 'float',
        'current_value' => 'float',
        'taken_in_range' => 'float',
        'available' => 'float',
        'taken' => 'float',
        'requested' => 'float',
        'approved' => 'float',
        'pending_change_or_cancel' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'calculation_id' => null,
        'name' => null,
        'period' => null,
        'unit' => null,
        'is_holiday' => null,
        'absence_name' => null,
        'range_from' => null,
        'range_to' => null,
        'range_text' => null,
        'start_value' => null,
        'target_value' => null,
        'total_value' => null,
        'carry_over' => null,
        'current_value' => null,
        'taken_in_range' => null,
        'available' => null,
        'taken' => null,
        'requested' => null,
        'approved' => null,
        'pending_change_or_cancel' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'calculation_id' => true,
        'name' => false,
        'period' => false,
        'unit' => false,
        'is_holiday' => false,
        'absence_name' => true,
        'range_from' => true,
        'range_to' => true,
        'range_text' => true,
        'start_value' => false,
        'target_value' => true,
        'total_value' => false,
        'carry_over' => false,
        'current_value' => false,
        'taken_in_range' => true,
        'available' => true,
        'taken' => true,
        'requested' => true,
        'approved' => true,
        'pending_change_or_cancel' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'calculation_id' => 'calculationId',
        'name' => 'name',
        'period' => 'period',
        'unit' => 'unit',
        'is_holiday' => 'isHoliday',
        'absence_name' => 'absenceName',
        'range_from' => 'rangeFrom',
        'range_to' => 'rangeTo',
        'range_text' => 'rangeText',
        'start_value' => 'startValue',
        'target_value' => 'targetValue',
        'total_value' => 'totalValue',
        'carry_over' => 'carryOver',
        'current_value' => 'currentValue',
        'taken_in_range' => 'takenInRange',
        'available' => 'available',
        'taken' => 'taken',
        'requested' => 'requested',
        'approved' => 'approved',
        'pending_change_or_cancel' => 'pendingChangeOrCancel'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'calculation_id' => 'setCalculationId',
        'name' => 'setName',
        'period' => 'setPeriod',
        'unit' => 'setUnit',
        'is_holiday' => 'setIsHoliday',
        'absence_name' => 'setAbsenceName',
        'range_from' => 'setRangeFrom',
        'range_to' => 'setRangeTo',
        'range_text' => 'setRangeText',
        'start_value' => 'setStartValue',
        'target_value' => 'setTargetValue',
        'total_value' => 'setTotalValue',
        'carry_over' => 'setCarryOver',
        'current_value' => 'setCurrentValue',
        'taken_in_range' => 'setTakenInRange',
        'available' => 'setAvailable',
        'taken' => 'setTaken',
        'requested' => 'setRequested',
        'approved' => 'setApproved',
        'pending_change_or_cancel' => 'setPendingChangeOrCancel'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'calculation_id' => 'getCalculationId',
        'name' => 'getName',
        'period' => 'getPeriod',
        'unit' => 'getUnit',
        'is_holiday' => 'getIsHoliday',
        'absence_name' => 'getAbsenceName',
        'range_from' => 'getRangeFrom',
        'range_to' => 'getRangeTo',
        'range_text' => 'getRangeText',
        'start_value' => 'getStartValue',
        'target_value' => 'getTargetValue',
        'total_value' => 'getTotalValue',
        'carry_over' => 'getCarryOver',
        'current_value' => 'getCurrentValue',
        'taken_in_range' => 'getTakenInRange',
        'available' => 'getAvailable',
        'taken' => 'getTaken',
        'requested' => 'getRequested',
        'approved' => 'getApproved',
        'pending_change_or_cancel' => 'getPendingChangeOrCancel'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const UNIT_DAYS = 'DAYS';
    public const UNIT_SECONDS = 'SECONDS';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getUnitAllowableValues()
    {
        return [
            self::UNIT_DAYS,
            self::UNIT_SECONDS,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('calculation_id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('period', $data ?? [], null);
        $this->setIfExists('unit', $data ?? [], null);
        $this->setIfExists('is_holiday', $data ?? [], null);
        $this->setIfExists('absence_name', $data ?? [], null);
        $this->setIfExists('range_from', $data ?? [], null);
        $this->setIfExists('range_to', $data ?? [], null);
        $this->setIfExists('range_text', $data ?? [], null);
        $this->setIfExists('start_value', $data ?? [], null);
        $this->setIfExists('target_value', $data ?? [], null);
        $this->setIfExists('total_value', $data ?? [], null);
        $this->setIfExists('carry_over', $data ?? [], null);
        $this->setIfExists('current_value', $data ?? [], null);
        $this->setIfExists('taken_in_range', $data ?? [], null);
        $this->setIfExists('available', $data ?? [], null);
        $this->setIfExists('taken', $data ?? [], null);
        $this->setIfExists('requested', $data ?? [], null);
        $this->setIfExists('approved', $data ?? [], null);
        $this->setIfExists('pending_change_or_cancel', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['calculation_id'] === null) {
            $invalidProperties[] = "'calculation_id' can't be null";
        }
        if (($this->container['calculation_id'] > 9007199254740991)) {
            $invalidProperties[] = "invalid value for 'calculation_id', must be smaller than or equal to 9007199254740991.";
        }

        if (($this->container['calculation_id'] < -9007199254740991)) {
            $invalidProperties[] = "invalid value for 'calculation_id', must be bigger than or equal to -9007199254740991.";
        }

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['period'] === null) {
            $invalidProperties[] = "'period' can't be null";
        }
        if ($this->container['unit'] === null) {
            $invalidProperties[] = "'unit' can't be null";
        }
        $allowedValues = self::getUnitAllowableValues();
        if (!is_null($this->container['unit']) && !in_array($this->container['unit'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'unit', must be one of '%s'",
                $this->container['unit'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['is_holiday'] === null) {
            $invalidProperties[] = "'is_holiday' can't be null";
        }
        if ($this->container['absence_name'] === null) {
            $invalidProperties[] = "'absence_name' can't be null";
        }
        if ($this->container['range_from'] === null) {
            $invalidProperties[] = "'range_from' can't be null";
        }
        if ($this->container['range_to'] === null) {
            $invalidProperties[] = "'range_to' can't be null";
        }
        if ($this->container['range_text'] === null) {
            $invalidProperties[] = "'range_text' can't be null";
        }
        if ($this->container['start_value'] === null) {
            $invalidProperties[] = "'start_value' can't be null";
        }
        if ($this->container['target_value'] === null) {
            $invalidProperties[] = "'target_value' can't be null";
        }
        if ($this->container['total_value'] === null) {
            $invalidProperties[] = "'total_value' can't be null";
        }
        if ($this->container['carry_over'] === null) {
            $invalidProperties[] = "'carry_over' can't be null";
        }
        if ($this->container['current_value'] === null) {
            $invalidProperties[] = "'current_value' can't be null";
        }
        if ($this->container['taken_in_range'] === null) {
            $invalidProperties[] = "'taken_in_range' can't be null";
        }
        if ($this->container['available'] === null) {
            $invalidProperties[] = "'available' can't be null";
        }
        if ($this->container['taken'] === null) {
            $invalidProperties[] = "'taken' can't be null";
        }
        if ($this->container['requested'] === null) {
            $invalidProperties[] = "'requested' can't be null";
        }
        if ($this->container['approved'] === null) {
            $invalidProperties[] = "'approved' can't be null";
        }
        if ($this->container['pending_change_or_cancel'] === null) {
            $invalidProperties[] = "'pending_change_or_cancel' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets calculation_id
     *
     * @return int
     */
    public function getCalculationId(): ?int
    {
        return $this->container['calculation_id'];
    }

    /**
     * Sets calculation_id
     *
     * @param int $calculation_id calculation_id
     *
     * @return $this
     */
    public function setCalculationId(?int $calculation_id): static
    {
        if (is_null($calculation_id)) {
            array_push($this->openAPINullablesSetToNull, 'calculation_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('calculation_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($calculation_id) && ($calculation_id > 9007199254740991)) {
            throw new InvalidArgumentException('invalid value for $calculation_id when calling GetDailyBalance200ResponseCalculationsInner., must be smaller than or equal to 9007199254740991.');
        }
        if (!is_null($calculation_id) && ($calculation_id < -9007199254740991)) {
            throw new InvalidArgumentException('invalid value for $calculation_id when calling GetDailyBalance200ResponseCalculationsInner., must be bigger than or equal to -9007199254740991.');
        }

        $this->container['calculation_id'] = $calculation_id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName(): string
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName(string $name): static
    {
        if (is_null($name)) {
            throw new InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets period
     *
     * @return string
     */
    public function getPeriod(): string
    {
        return $this->container['period'];
    }

    /**
     * Sets period
     *
     * @param string $period period
     *
     * @return $this
     */
    public function setPeriod(string $period): static
    {
        if (is_null($period)) {
            throw new InvalidArgumentException('non-nullable period cannot be null');
        }
        $this->container['period'] = $period;

        return $this;
    }

    /**
     * Gets unit
     *
     * @return string
     */
    public function getUnit(): string
    {
        return $this->container['unit'];
    }

    /**
     * Sets unit
     *
     * @param string $unit unit
     *
     * @return $this
     */
    public function setUnit(string $unit): static
    {
        if (is_null($unit)) {
            throw new InvalidArgumentException('non-nullable unit cannot be null');
        }
        $allowedValues = self::getUnitAllowableValues();
        if (!in_array($unit, $allowedValues, true)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'unit', must be one of '%s'",
                    $unit,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['unit'] = $unit;

        return $this;
    }

    /**
     * Gets is_holiday
     *
     * @return bool
     */
    public function getIsHoliday(): bool
    {
        return $this->container['is_holiday'];
    }

    /**
     * Sets is_holiday
     *
     * @param bool $is_holiday is_holiday
     *
     * @return $this
     */
    public function setIsHoliday(bool $is_holiday): static
    {
        if (is_null($is_holiday)) {
            throw new InvalidArgumentException('non-nullable is_holiday cannot be null');
        }
        $this->container['is_holiday'] = $is_holiday;

        return $this;
    }

    /**
     * Gets absence_name
     *
     * @return string
     */
    public function getAbsenceName(): ?string
    {
        return $this->container['absence_name'];
    }

    /**
     * Sets absence_name
     *
     * @param string $absence_name absence_name
     *
     * @return $this
     */
    public function setAbsenceName(?string $absence_name): static
    {
        if (is_null($absence_name)) {
            array_push($this->openAPINullablesSetToNull, 'absence_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('absence_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['absence_name'] = $absence_name;

        return $this;
    }

    /**
     * Gets range_from
     *
     * @return string
     */
    public function getRangeFrom(): ?string
    {
        return $this->container['range_from'];
    }

    /**
     * Sets range_from
     *
     * @param string $range_from range_from
     *
     * @return $this
     */
    public function setRangeFrom(?string $range_from): static
    {
        if (is_null($range_from)) {
            array_push($this->openAPINullablesSetToNull, 'range_from');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('range_from', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['range_from'] = $range_from;

        return $this;
    }

    /**
     * Gets range_to
     *
     * @return string
     */
    public function getRangeTo(): ?string
    {
        return $this->container['range_to'];
    }

    /**
     * Sets range_to
     *
     * @param string $range_to range_to
     *
     * @return $this
     */
    public function setRangeTo(?string $range_to): static
    {
        if (is_null($range_to)) {
            array_push($this->openAPINullablesSetToNull, 'range_to');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('range_to', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['range_to'] = $range_to;

        return $this;
    }

    /**
     * Gets range_text
     *
     * @return string
     */
    public function getRangeText(): ?string
    {
        return $this->container['range_text'];
    }

    /**
     * Sets range_text
     *
     * @param string $range_text range_text
     *
     * @return $this
     */
    public function setRangeText(?string $range_text): static
    {
        if (is_null($range_text)) {
            array_push($this->openAPINullablesSetToNull, 'range_text');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('range_text', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['range_text'] = $range_text;

        return $this;
    }

    /**
     * Gets start_value
     *
     * @return float
     */
    public function getStartValue(): float
    {
        return $this->container['start_value'];
    }

    /**
     * Sets start_value
     *
     * @param float $start_value start_value
     *
     * @return $this
     */
    public function setStartValue(float $start_value): static
    {
        if (is_null($start_value)) {
            throw new InvalidArgumentException('non-nullable start_value cannot be null');
        }
        $this->container['start_value'] = $start_value;

        return $this;
    }

    /**
     * Gets target_value
     *
     * @return float
     */
    public function getTargetValue(): ?float
    {
        return $this->container['target_value'];
    }

    /**
     * Sets target_value
     *
     * @param float $target_value target_value
     *
     * @return $this
     */
    public function setTargetValue(?float $target_value): static
    {
        if (is_null($target_value)) {
            array_push($this->openAPINullablesSetToNull, 'target_value');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('target_value', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['target_value'] = $target_value;

        return $this;
    }

    /**
     * Gets total_value
     *
     * @return float
     */
    public function getTotalValue(): float
    {
        return $this->container['total_value'];
    }

    /**
     * Sets total_value
     *
     * @param float $total_value total_value
     *
     * @return $this
     */
    public function setTotalValue(float $total_value): static
    {
        if (is_null($total_value)) {
            throw new InvalidArgumentException('non-nullable total_value cannot be null');
        }
        $this->container['total_value'] = $total_value;

        return $this;
    }

    /**
     * Gets carry_over
     *
     * @return float
     */
    public function getCarryOver(): float
    {
        return $this->container['carry_over'];
    }

    /**
     * Sets carry_over
     *
     * @param float $carry_over carry_over
     *
     * @return $this
     */
    public function setCarryOver(float $carry_over): static
    {
        if (is_null($carry_over)) {
            throw new InvalidArgumentException('non-nullable carry_over cannot be null');
        }
        $this->container['carry_over'] = $carry_over;

        return $this;
    }

    /**
     * Gets current_value
     *
     * @return float
     */
    public function getCurrentValue(): float
    {
        return $this->container['current_value'];
    }

    /**
     * Sets current_value
     *
     * @param float $current_value current_value
     *
     * @return $this
     */
    public function setCurrentValue(float $current_value): static
    {
        if (is_null($current_value)) {
            throw new InvalidArgumentException('non-nullable current_value cannot be null');
        }
        $this->container['current_value'] = $current_value;

        return $this;
    }

    /**
     * Gets taken_in_range
     *
     * @return float
     */
    public function getTakenInRange(): ?float
    {
        return $this->container['taken_in_range'];
    }

    /**
     * Sets taken_in_range
     *
     * @param float $taken_in_range taken_in_range
     *
     * @return $this
     */
    public function setTakenInRange(?float $taken_in_range): static
    {
        if (is_null($taken_in_range)) {
            array_push($this->openAPINullablesSetToNull, 'taken_in_range');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('taken_in_range', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['taken_in_range'] = $taken_in_range;

        return $this;
    }

    /**
     * Gets available
     *
     * @return float
     */
    public function getAvailable(): ?float
    {
        return $this->container['available'];
    }

    /**
     * Sets available
     *
     * @param float $available available
     *
     * @return $this
     */
    public function setAvailable(?float $available): static
    {
        if (is_null($available)) {
            array_push($this->openAPINullablesSetToNull, 'available');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('available', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['available'] = $available;

        return $this;
    }

    /**
     * Gets taken
     *
     * @return float
     */
    public function getTaken(): ?float
    {
        return $this->container['taken'];
    }

    /**
     * Sets taken
     *
     * @param float $taken taken
     *
     * @return $this
     */
    public function setTaken(?float $taken): static
    {
        if (is_null($taken)) {
            array_push($this->openAPINullablesSetToNull, 'taken');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('taken', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['taken'] = $taken;

        return $this;
    }

    /**
     * Gets requested
     *
     * @return float
     */
    public function getRequested(): ?float
    {
        return $this->container['requested'];
    }

    /**
     * Sets requested
     *
     * @param float $requested requested
     *
     * @return $this
     */
    public function setRequested(?float $requested): static
    {
        if (is_null($requested)) {
            array_push($this->openAPINullablesSetToNull, 'requested');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('requested', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['requested'] = $requested;

        return $this;
    }

    /**
     * Gets approved
     *
     * @return float
     */
    public function getApproved(): ?float
    {
        return $this->container['approved'];
    }

    /**
     * Sets approved
     *
     * @param float $approved approved
     *
     * @return $this
     */
    public function setApproved(?float $approved): static
    {
        if (is_null($approved)) {
            array_push($this->openAPINullablesSetToNull, 'approved');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('approved', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['approved'] = $approved;

        return $this;
    }

    /**
     * Gets pending_change_or_cancel
     *
     * @return float
     */
    public function getPendingChangeOrCancel(): ?float
    {
        return $this->container['pending_change_or_cancel'];
    }

    /**
     * Sets pending_change_or_cancel
     *
     * @param float $pending_change_or_cancel pending_change_or_cancel
     *
     * @return $this
     */
    public function setPendingChangeOrCancel(?float $pending_change_or_cancel): static
    {
        if (is_null($pending_change_or_cancel)) {
            array_push($this->openAPINullablesSetToNull, 'pending_change_or_cancel');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('pending_change_or_cancel', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['pending_change_or_cancel'] = $pending_change_or_cancel;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


