<?php
/**
 * GetPerson200ResponseTimeRecording
 *
 * PHP version 8.1
 *
 * @package  TimecardClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * timeCard REST facade
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.4.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TimecardClient\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use TimecardClient\ObjectSerializer;

/**
 * GetPerson200ResponseTimeRecording Class Doc Comment
 *
 * @package  TimecardClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class GetPerson200ResponseTimeRecording implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'getPerson_200_response_timeRecording';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'workingProfile' => '\TimecardClient\Model\GetPerson200ResponseTimeRecordingWorkingProfile',
        'calculationTemplates' => '\TimecardClient\Model\GetPerson200ResponseTimeRecordingCalculationTemplates',
        'holiday' => '\TimecardClient\Model\GetPerson200ResponseTimeRecordingHoliday',
        'firstDayOfMonth' => 'int',
        'hasOpenRequests' => 'bool',
        'supervisors' => '\TimecardClient\Model\GetPerson200ResponseTimeRecordingSupervisorsInner[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'workingProfile' => null,
        'calculationTemplates' => null,
        'holiday' => null,
        'firstDayOfMonth' => null,
        'hasOpenRequests' => null,
        'supervisors' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'workingProfile' => false,
        'calculationTemplates' => false,
        'holiday' => false,
        'firstDayOfMonth' => false,
        'hasOpenRequests' => true,
        'supervisors' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'workingProfile' => 'workingProfile',
        'calculationTemplates' => 'calculationTemplates',
        'holiday' => 'holiday',
        'firstDayOfMonth' => 'firstDayOfMonth',
        'hasOpenRequests' => 'hasOpenRequests',
        'supervisors' => 'supervisors'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'workingProfile' => 'setWorkingProfile',
        'calculationTemplates' => 'setCalculationTemplates',
        'holiday' => 'setHoliday',
        'firstDayOfMonth' => 'setFirstDayOfMonth',
        'hasOpenRequests' => 'setHasOpenRequests',
        'supervisors' => 'setSupervisors'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'workingProfile' => 'getWorkingProfile',
        'calculationTemplates' => 'getCalculationTemplates',
        'holiday' => 'getHoliday',
        'firstDayOfMonth' => 'getFirstDayOfMonth',
        'hasOpenRequests' => 'getHasOpenRequests',
        'supervisors' => 'getSupervisors'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('workingProfile', $data ?? [], null);
        $this->setIfExists('calculationTemplates', $data ?? [], null);
        $this->setIfExists('holiday', $data ?? [], null);
        $this->setIfExists('firstDayOfMonth', $data ?? [], null);
        $this->setIfExists('hasOpenRequests', $data ?? [], null);
        $this->setIfExists('supervisors', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['workingProfile'] === null) {
            $invalidProperties[] = "'workingProfile' can't be null";
        }
        if ($this->container['calculationTemplates'] === null) {
            $invalidProperties[] = "'calculationTemplates' can't be null";
        }
        if ($this->container['holiday'] === null) {
            $invalidProperties[] = "'holiday' can't be null";
        }
        if ($this->container['firstDayOfMonth'] === null) {
            $invalidProperties[] = "'firstDayOfMonth' can't be null";
        }
        if (($this->container['firstDayOfMonth'] > 9007199254740991)) {
            $invalidProperties[] = "invalid value for 'firstDayOfMonth', must be smaller than or equal to 9007199254740991.";
        }

        if (($this->container['firstDayOfMonth'] < -9007199254740991)) {
            $invalidProperties[] = "invalid value for 'firstDayOfMonth', must be bigger than or equal to -9007199254740991.";
        }

        if ($this->container['hasOpenRequests'] === null) {
            $invalidProperties[] = "'hasOpenRequests' can't be null";
        }
        if ($this->container['supervisors'] === null) {
            $invalidProperties[] = "'supervisors' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets workingProfile
     *
     * @return \TimecardClient\Model\GetPerson200ResponseTimeRecordingWorkingProfile
     */
    public function getWorkingProfile(): \TimecardClient\Model\GetPerson200ResponseTimeRecordingWorkingProfile
    {
        return $this->container['workingProfile'];
    }

    /**
     * Sets workingProfile
     *
     * @param \TimecardClient\Model\GetPerson200ResponseTimeRecordingWorkingProfile $workingProfile workingProfile
     *
     * @return $this
     */
    public function setWorkingProfile(\TimecardClient\Model\GetPerson200ResponseTimeRecordingWorkingProfile $workingProfile): static
    {
        if (is_null($workingProfile)) {
            throw new InvalidArgumentException('non-nullable workingProfile cannot be null');
        }
        $this->container['workingProfile'] = $workingProfile;

        return $this;
    }

    /**
     * Gets calculationTemplates
     *
     * @return \TimecardClient\Model\GetPerson200ResponseTimeRecordingCalculationTemplates
     */
    public function getCalculationTemplates(): \TimecardClient\Model\GetPerson200ResponseTimeRecordingCalculationTemplates
    {
        return $this->container['calculationTemplates'];
    }

    /**
     * Sets calculationTemplates
     *
     * @param \TimecardClient\Model\GetPerson200ResponseTimeRecordingCalculationTemplates $calculationTemplates calculationTemplates
     *
     * @return $this
     */
    public function setCalculationTemplates(\TimecardClient\Model\GetPerson200ResponseTimeRecordingCalculationTemplates $calculationTemplates): static
    {
        if (is_null($calculationTemplates)) {
            throw new InvalidArgumentException('non-nullable calculationTemplates cannot be null');
        }
        $this->container['calculationTemplates'] = $calculationTemplates;

        return $this;
    }

    /**
     * Gets holiday
     *
     * @return \TimecardClient\Model\GetPerson200ResponseTimeRecordingHoliday
     */
    public function getHoliday(): \TimecardClient\Model\GetPerson200ResponseTimeRecordingHoliday
    {
        return $this->container['holiday'];
    }

    /**
     * Sets holiday
     *
     * @param \TimecardClient\Model\GetPerson200ResponseTimeRecordingHoliday $holiday holiday
     *
     * @return $this
     */
    public function setHoliday(\TimecardClient\Model\GetPerson200ResponseTimeRecordingHoliday $holiday): static
    {
        if (is_null($holiday)) {
            throw new InvalidArgumentException('non-nullable holiday cannot be null');
        }
        $this->container['holiday'] = $holiday;

        return $this;
    }

    /**
     * Gets firstDayOfMonth
     *
     * @return int
     */
    public function getFirstDayOfMonth(): int
    {
        return $this->container['firstDayOfMonth'];
    }

    /**
     * Sets firstDayOfMonth
     *
     * @param int $firstDayOfMonth firstDayOfMonth
     *
     * @return $this
     */
    public function setFirstDayOfMonth(int $firstDayOfMonth): static
    {
        if (is_null($firstDayOfMonth)) {
            throw new InvalidArgumentException('non-nullable firstDayOfMonth cannot be null');
        }

        if (($firstDayOfMonth > 9007199254740991)) {
            throw new InvalidArgumentException('invalid value for $firstDayOfMonth when calling GetPerson200ResponseTimeRecording., must be smaller than or equal to 9007199254740991.');
        }
        if (($firstDayOfMonth < -9007199254740991)) {
            throw new InvalidArgumentException('invalid value for $firstDayOfMonth when calling GetPerson200ResponseTimeRecording., must be bigger than or equal to -9007199254740991.');
        }

        $this->container['firstDayOfMonth'] = $firstDayOfMonth;

        return $this;
    }

    /**
     * Gets hasOpenRequests
     *
     * @return bool
     */
    public function getHasOpenRequests(): ?bool
    {
        return $this->container['hasOpenRequests'];
    }

    /**
     * Sets hasOpenRequests
     *
     * @param bool $hasOpenRequests hasOpenRequests
     *
     * @return $this
     */
    public function setHasOpenRequests(?bool $hasOpenRequests): static
    {
        if (is_null($hasOpenRequests)) {
            array_push($this->openAPINullablesSetToNull, 'hasOpenRequests');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('hasOpenRequests', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['hasOpenRequests'] = $hasOpenRequests;

        return $this;
    }

    /**
     * Gets supervisors
     *
     * @return \TimecardClient\Model\GetPerson200ResponseTimeRecordingSupervisorsInner[]
     */
    public function getSupervisors(): array
    {
        return $this->container['supervisors'];
    }

    /**
     * Sets supervisors
     *
     * @param \TimecardClient\Model\GetPerson200ResponseTimeRecordingSupervisorsInner[] $supervisors supervisors
     *
     * @return $this
     */
    public function setSupervisors(array $supervisors): static
    {
        if (is_null($supervisors)) {
            throw new InvalidArgumentException('non-nullable supervisors cannot be null');
        }
        $this->container['supervisors'] = $supervisors;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


