<?php
/**
 * GetPersonCalendar200ResponseSickDays
 *
 * PHP version 8.1
 *
 * @package  TimecardClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * timeCard REST facade
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.2
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TimecardClient\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use TimecardClient\ObjectSerializer;

/**
 * GetPersonCalendar200ResponseSickDays Class Doc Comment
 *
 * @package  TimecardClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class GetPersonCalendar200ResponseSickDays implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'getPersonCalendar_200_response_sickDays';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'certificateNotRequired' => '\TimecardClient\Model\GetPersonCalendar200ResponsePublicHolidaysInner[]',
        'certificateMissing' => '\TimecardClient\Model\GetPersonCalendar200ResponsePublicHolidaysInner[]',
        'certificateAvailable' => '\TimecardClient\Model\GetPersonCalendar200ResponsePublicHolidaysInner[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'certificateNotRequired' => null,
        'certificateMissing' => null,
        'certificateAvailable' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'certificateNotRequired' => false,
        'certificateMissing' => false,
        'certificateAvailable' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'certificateNotRequired' => 'certificateNotRequired',
        'certificateMissing' => 'certificateMissing',
        'certificateAvailable' => 'certificateAvailable'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'certificateNotRequired' => 'setCertificateNotRequired',
        'certificateMissing' => 'setCertificateMissing',
        'certificateAvailable' => 'setCertificateAvailable'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'certificateNotRequired' => 'getCertificateNotRequired',
        'certificateMissing' => 'getCertificateMissing',
        'certificateAvailable' => 'getCertificateAvailable'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('certificateNotRequired', $data ?? [], null);
        $this->setIfExists('certificateMissing', $data ?? [], null);
        $this->setIfExists('certificateAvailable', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['certificateNotRequired'] === null) {
            $invalidProperties[] = "'certificateNotRequired' can't be null";
        }
        if ($this->container['certificateMissing'] === null) {
            $invalidProperties[] = "'certificateMissing' can't be null";
        }
        if ($this->container['certificateAvailable'] === null) {
            $invalidProperties[] = "'certificateAvailable' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets certificateNotRequired
     *
     * @return \TimecardClient\Model\GetPersonCalendar200ResponsePublicHolidaysInner[]
     */
    public function getCertificateNotRequired(): array
    {
        return $this->container['certificateNotRequired'];
    }

    /**
     * Sets certificateNotRequired
     *
     * @param \TimecardClient\Model\GetPersonCalendar200ResponsePublicHolidaysInner[] $certificateNotRequired certificateNotRequired
     *
     * @return $this
     */
    public function setCertificateNotRequired(array $certificateNotRequired): static
    {
        if (is_null($certificateNotRequired)) {
            throw new InvalidArgumentException('non-nullable certificateNotRequired cannot be null');
        }
        $this->container['certificateNotRequired'] = $certificateNotRequired;

        return $this;
    }

    /**
     * Gets certificateMissing
     *
     * @return \TimecardClient\Model\GetPersonCalendar200ResponsePublicHolidaysInner[]
     */
    public function getCertificateMissing(): array
    {
        return $this->container['certificateMissing'];
    }

    /**
     * Sets certificateMissing
     *
     * @param \TimecardClient\Model\GetPersonCalendar200ResponsePublicHolidaysInner[] $certificateMissing certificateMissing
     *
     * @return $this
     */
    public function setCertificateMissing(array $certificateMissing): static
    {
        if (is_null($certificateMissing)) {
            throw new InvalidArgumentException('non-nullable certificateMissing cannot be null');
        }
        $this->container['certificateMissing'] = $certificateMissing;

        return $this;
    }

    /**
     * Gets certificateAvailable
     *
     * @return \TimecardClient\Model\GetPersonCalendar200ResponsePublicHolidaysInner[]
     */
    public function getCertificateAvailable(): array
    {
        return $this->container['certificateAvailable'];
    }

    /**
     * Sets certificateAvailable
     *
     * @param \TimecardClient\Model\GetPersonCalendar200ResponsePublicHolidaysInner[] $certificateAvailable certificateAvailable
     *
     * @return $this
     */
    public function setCertificateAvailable(array $certificateAvailable): static
    {
        if (is_null($certificateAvailable)) {
            throw new InvalidArgumentException('non-nullable certificateAvailable cannot be null');
        }
        $this->container['certificateAvailable'] = $certificateAvailable;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


