<?php
/**
 * ListCarryOvers200ResponseItemsInner
 *
 * PHP version 8.1
 *
 * @package  TimecardClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * timeCard REST facade
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.4.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TimecardClient\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use TimecardClient\ObjectSerializer;

/**
 * ListCarryOvers200ResponseItemsInner Class Doc Comment
 *
 * @package  TimecardClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class ListCarryOvers200ResponseItemsInner implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'listCarryOvers_200_response_items_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'id' => 'int',
        'personId' => 'int',
        'calculationId' => 'int',
        'calcAccountId' => 'int',
        'balanceDate' => 'string',
        'unit' => 'string',
        'value' => 'float',
        'formattedValue' => 'string',
        'reason' => 'string',
        'addToTotal' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'id' => null,
        'personId' => null,
        'calculationId' => null,
        'calcAccountId' => null,
        'balanceDate' => null,
        'unit' => null,
        'value' => null,
        'formattedValue' => null,
        'reason' => null,
        'addToTotal' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'id' => true,
        'personId' => true,
        'calculationId' => true,
        'calcAccountId' => true,
        'balanceDate' => false,
        'unit' => false,
        'value' => false,
        'formattedValue' => true,
        'reason' => true,
        'addToTotal' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'id' => 'id',
        'personId' => 'personId',
        'calculationId' => 'calculationId',
        'calcAccountId' => 'calcAccountId',
        'balanceDate' => 'balanceDate',
        'unit' => 'unit',
        'value' => 'value',
        'formattedValue' => 'formattedValue',
        'reason' => 'reason',
        'addToTotal' => 'addToTotal'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'id' => 'setId',
        'personId' => 'setPersonId',
        'calculationId' => 'setCalculationId',
        'calcAccountId' => 'setCalcAccountId',
        'balanceDate' => 'setBalanceDate',
        'unit' => 'setUnit',
        'value' => 'setValue',
        'formattedValue' => 'setFormattedValue',
        'reason' => 'setReason',
        'addToTotal' => 'setAddToTotal'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'id' => 'getId',
        'personId' => 'getPersonId',
        'calculationId' => 'getCalculationId',
        'calcAccountId' => 'getCalcAccountId',
        'balanceDate' => 'getBalanceDate',
        'unit' => 'getUnit',
        'value' => 'getValue',
        'formattedValue' => 'getFormattedValue',
        'reason' => 'getReason',
        'addToTotal' => 'getAddToTotal'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const UNIT_DAYS = 'DAYS';
    public const UNIT_SECONDS = 'SECONDS';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getUnitAllowableValues()
    {
        return [
            self::UNIT_DAYS,
            self::UNIT_SECONDS,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('personId', $data ?? [], null);
        $this->setIfExists('calculationId', $data ?? [], null);
        $this->setIfExists('calcAccountId', $data ?? [], null);
        $this->setIfExists('balanceDate', $data ?? [], null);
        $this->setIfExists('unit', $data ?? [], null);
        $this->setIfExists('value', $data ?? [], null);
        $this->setIfExists('formattedValue', $data ?? [], null);
        $this->setIfExists('reason', $data ?? [], null);
        $this->setIfExists('addToTotal', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if (($this->container['id'] > 9007199254740991)) {
            $invalidProperties[] = "invalid value for 'id', must be smaller than or equal to 9007199254740991.";
        }

        if (($this->container['id'] < -9007199254740991)) {
            $invalidProperties[] = "invalid value for 'id', must be bigger than or equal to -9007199254740991.";
        }

        if ($this->container['personId'] === null) {
            $invalidProperties[] = "'personId' can't be null";
        }
        if (($this->container['personId'] > 9007199254740991)) {
            $invalidProperties[] = "invalid value for 'personId', must be smaller than or equal to 9007199254740991.";
        }

        if (($this->container['personId'] < -9007199254740991)) {
            $invalidProperties[] = "invalid value for 'personId', must be bigger than or equal to -9007199254740991.";
        }

        if ($this->container['calculationId'] === null) {
            $invalidProperties[] = "'calculationId' can't be null";
        }
        if (($this->container['calculationId'] > 9007199254740991)) {
            $invalidProperties[] = "invalid value for 'calculationId', must be smaller than or equal to 9007199254740991.";
        }

        if (($this->container['calculationId'] < -9007199254740991)) {
            $invalidProperties[] = "invalid value for 'calculationId', must be bigger than or equal to -9007199254740991.";
        }

        if ($this->container['calcAccountId'] === null) {
            $invalidProperties[] = "'calcAccountId' can't be null";
        }
        if (($this->container['calcAccountId'] > 9007199254740991)) {
            $invalidProperties[] = "invalid value for 'calcAccountId', must be smaller than or equal to 9007199254740991.";
        }

        if (($this->container['calcAccountId'] < -9007199254740991)) {
            $invalidProperties[] = "invalid value for 'calcAccountId', must be bigger than or equal to -9007199254740991.";
        }

        if ($this->container['balanceDate'] === null) {
            $invalidProperties[] = "'balanceDate' can't be null";
        }
        if ($this->container['unit'] === null) {
            $invalidProperties[] = "'unit' can't be null";
        }
        $allowedValues = self::getUnitAllowableValues();
        if (!is_null($this->container['unit']) && !in_array($this->container['unit'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'unit', must be one of '%s'",
                $this->container['unit'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['value'] === null) {
            $invalidProperties[] = "'value' can't be null";
        }
        if ($this->container['formattedValue'] === null) {
            $invalidProperties[] = "'formattedValue' can't be null";
        }
        if ($this->container['reason'] === null) {
            $invalidProperties[] = "'reason' can't be null";
        }
        if ($this->container['addToTotal'] === null) {
            $invalidProperties[] = "'addToTotal' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId(): ?int
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return $this
     */
    public function setId(?int $id): static
    {
        if (is_null($id)) {
            array_push($this->openAPINullablesSetToNull, 'id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($id) && ($id > 9007199254740991)) {
            throw new InvalidArgumentException('invalid value for $id when calling ListCarryOvers200ResponseItemsInner., must be smaller than or equal to 9007199254740991.');
        }
        if (!is_null($id) && ($id < -9007199254740991)) {
            throw new InvalidArgumentException('invalid value for $id when calling ListCarryOvers200ResponseItemsInner., must be bigger than or equal to -9007199254740991.');
        }

        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets personId
     *
     * @return int
     */
    public function getPersonId(): ?int
    {
        return $this->container['personId'];
    }

    /**
     * Sets personId
     *
     * @param int $personId personId
     *
     * @return $this
     */
    public function setPersonId(?int $personId): static
    {
        if (is_null($personId)) {
            array_push($this->openAPINullablesSetToNull, 'personId');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('personId', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($personId) && ($personId > 9007199254740991)) {
            throw new InvalidArgumentException('invalid value for $personId when calling ListCarryOvers200ResponseItemsInner., must be smaller than or equal to 9007199254740991.');
        }
        if (!is_null($personId) && ($personId < -9007199254740991)) {
            throw new InvalidArgumentException('invalid value for $personId when calling ListCarryOvers200ResponseItemsInner., must be bigger than or equal to -9007199254740991.');
        }

        $this->container['personId'] = $personId;

        return $this;
    }

    /**
     * Gets calculationId
     *
     * @return int
     */
    public function getCalculationId(): ?int
    {
        return $this->container['calculationId'];
    }

    /**
     * Sets calculationId
     *
     * @param int $calculationId calculationId
     *
     * @return $this
     */
    public function setCalculationId(?int $calculationId): static
    {
        if (is_null($calculationId)) {
            array_push($this->openAPINullablesSetToNull, 'calculationId');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('calculationId', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($calculationId) && ($calculationId > 9007199254740991)) {
            throw new InvalidArgumentException('invalid value for $calculationId when calling ListCarryOvers200ResponseItemsInner., must be smaller than or equal to 9007199254740991.');
        }
        if (!is_null($calculationId) && ($calculationId < -9007199254740991)) {
            throw new InvalidArgumentException('invalid value for $calculationId when calling ListCarryOvers200ResponseItemsInner., must be bigger than or equal to -9007199254740991.');
        }

        $this->container['calculationId'] = $calculationId;

        return $this;
    }

    /**
     * Gets calcAccountId
     *
     * @return int
     */
    public function getCalcAccountId(): ?int
    {
        return $this->container['calcAccountId'];
    }

    /**
     * Sets calcAccountId
     *
     * @param int $calcAccountId calcAccountId
     *
     * @return $this
     */
    public function setCalcAccountId(?int $calcAccountId): static
    {
        if (is_null($calcAccountId)) {
            array_push($this->openAPINullablesSetToNull, 'calcAccountId');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('calcAccountId', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($calcAccountId) && ($calcAccountId > 9007199254740991)) {
            throw new InvalidArgumentException('invalid value for $calcAccountId when calling ListCarryOvers200ResponseItemsInner., must be smaller than or equal to 9007199254740991.');
        }
        if (!is_null($calcAccountId) && ($calcAccountId < -9007199254740991)) {
            throw new InvalidArgumentException('invalid value for $calcAccountId when calling ListCarryOvers200ResponseItemsInner., must be bigger than or equal to -9007199254740991.');
        }

        $this->container['calcAccountId'] = $calcAccountId;

        return $this;
    }

    /**
     * Gets balanceDate
     *
     * @return string
     */
    public function getBalanceDate(): string
    {
        return $this->container['balanceDate'];
    }

    /**
     * Sets balanceDate
     *
     * @param string $balanceDate balanceDate
     *
     * @return $this
     */
    public function setBalanceDate(string $balanceDate): static
    {
        if (is_null($balanceDate)) {
            throw new InvalidArgumentException('non-nullable balanceDate cannot be null');
        }
        $this->container['balanceDate'] = $balanceDate;

        return $this;
    }

    /**
     * Gets unit
     *
     * @return string
     */
    public function getUnit(): string
    {
        return $this->container['unit'];
    }

    /**
     * Sets unit
     *
     * @param string $unit unit
     *
     * @return $this
     */
    public function setUnit(string $unit): static
    {
        if (is_null($unit)) {
            throw new InvalidArgumentException('non-nullable unit cannot be null');
        }
        $allowedValues = self::getUnitAllowableValues();
        if (!in_array($unit, $allowedValues, true)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'unit', must be one of '%s'",
                    $unit,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['unit'] = $unit;

        return $this;
    }

    /**
     * Gets value
     *
     * @return float
     */
    public function getValue(): float
    {
        return $this->container['value'];
    }

    /**
     * Sets value
     *
     * @param float $value value
     *
     * @return $this
     */
    public function setValue(float $value): static
    {
        if (is_null($value)) {
            throw new InvalidArgumentException('non-nullable value cannot be null');
        }
        $this->container['value'] = $value;

        return $this;
    }

    /**
     * Gets formattedValue
     *
     * @return string
     */
    public function getFormattedValue(): ?string
    {
        return $this->container['formattedValue'];
    }

    /**
     * Sets formattedValue
     *
     * @param string $formattedValue formattedValue
     *
     * @return $this
     */
    public function setFormattedValue(?string $formattedValue): static
    {
        if (is_null($formattedValue)) {
            array_push($this->openAPINullablesSetToNull, 'formattedValue');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('formattedValue', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['formattedValue'] = $formattedValue;

        return $this;
    }

    /**
     * Gets reason
     *
     * @return string
     */
    public function getReason(): ?string
    {
        return $this->container['reason'];
    }

    /**
     * Sets reason
     *
     * @param string $reason reason
     *
     * @return $this
     */
    public function setReason(?string $reason): static
    {
        if (is_null($reason)) {
            array_push($this->openAPINullablesSetToNull, 'reason');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('reason', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['reason'] = $reason;

        return $this;
    }

    /**
     * Gets addToTotal
     *
     * @return bool
     */
    public function getAddToTotal(): bool
    {
        return $this->container['addToTotal'];
    }

    /**
     * Sets addToTotal
     *
     * @param bool $addToTotal addToTotal
     *
     * @return $this
     */
    public function setAddToTotal(bool $addToTotal): static
    {
        if (is_null($addToTotal)) {
            throw new InvalidArgumentException('non-nullable addToTotal cannot be null');
        }
        $this->container['addToTotal'] = $addToTotal;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


