<?php
/**
 * AuditApi
 * PHP version 8.1
 *
 * @package  TimecardClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * timeCard REST facade
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.4.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TimecardClient\Api;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use TimecardClient\ApiException;
use TimecardClient\Configuration;
use TimecardClient\HeaderSelector;
use TimecardClient\FormDataProcessor;
use TimecardClient\ObjectSerializer;

/**
 * AuditApi Class Doc Comment
 *
 * @package  TimecardClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AuditApi
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getAuditEvent' => [
            'application/json',
        ],
        'listAuditEvents' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation getAuditEvent
     *
     * Read one audit event
     *
     * @param  string $eventId eventId (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAuditEvent'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \TimecardClient\Model\GetAuditEvent200Response|\TimecardClient\Model\Problem
     */
    public function getAuditEvent(
        string $eventId,
        string $contentType = self::contentTypes['getAuditEvent'][0]
    ): \TimecardClient\Model\GetAuditEvent200Response|\TimecardClient\Model\Problem
    {
        list($response) = $this->getAuditEventWithHttpInfo($eventId, $contentType);
        return $response;
    }

    /**
     * Operation getAuditEventWithHttpInfo
     *
     * Read one audit event
     *
     * @param  string $eventId (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAuditEvent'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \TimecardClient\Model\GetAuditEvent200Response|\TimecardClient\Model\Problem|\TimecardClient\Model\Problem|\TimecardClient\Model\Problem|\TimecardClient\Model\Problem|\TimecardClient\Model\Problem|\TimecardClient\Model\Problem|\TimecardClient\Model\Problem|\TimecardClient\Model\Problem, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAuditEventWithHttpInfo(
        string $eventId,
        string $contentType = self::contentTypes['getAuditEvent'][0]
    ): array
    {
        $request = $this->getAuditEventRequest($eventId, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\TimecardClient\Model\GetAuditEvent200Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\TimecardClient\Model\Problem',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\TimecardClient\Model\Problem',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\TimecardClient\Model\Problem',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\TimecardClient\Model\Problem',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\TimecardClient\Model\Problem',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\TimecardClient\Model\Problem',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\TimecardClient\Model\Problem',
                        $request,
                        $response,
                    );
                case 503:
                    return $this->handleResponseWithDataType(
                        '\TimecardClient\Model\Problem',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\TimecardClient\Model\GetAuditEvent200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TimecardClient\Model\GetAuditEvent200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TimecardClient\Model\Problem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TimecardClient\Model\Problem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TimecardClient\Model\Problem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TimecardClient\Model\Problem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TimecardClient\Model\Problem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TimecardClient\Model\Problem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TimecardClient\Model\Problem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TimecardClient\Model\Problem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation getAuditEventAsync
     *
     * Read one audit event
     *
     * @param  string $eventId (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAuditEvent'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getAuditEventAsync(
        string $eventId,
        string $contentType = self::contentTypes['getAuditEvent'][0]
    ): PromiseInterface
    {
        return $this->getAuditEventAsyncWithHttpInfo($eventId, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAuditEventAsyncWithHttpInfo
     *
     * Read one audit event
     *
     * @param  string $eventId (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAuditEvent'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getAuditEventAsyncWithHttpInfo(
        string $eventId,
        string $contentType = self::contentTypes['getAuditEvent'][0]
    ): PromiseInterface
    {
        $returnType = '\TimecardClient\Model\GetAuditEvent200Response';
        $request = $this->getAuditEventRequest($eventId, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAuditEvent'
     *
     * @param  string $eventId (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAuditEvent'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getAuditEventRequest(
        string $eventId,
        string $contentType = self::contentTypes['getAuditEvent'][0]
    ): Request
    {

        // verify the required parameter 'eventId' is set
        if ($eventId === null || (is_array($eventId) && count($eventId) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $eventId when calling getAuditEvent'
            );
        }
        if (strlen($eventId) > 64) {
            throw new InvalidArgumentException('invalid length for "$eventId" when calling AuditApi.getAuditEvent, must be smaller than or equal to 64.');
        }
        if (strlen($eventId) < 1) {
            throw new InvalidArgumentException('invalid length for "$eventId" when calling AuditApi.getAuditEvent, must be bigger than or equal to 1.');
        }
        

        $resourcePath = '/v1/audit-events/{eventId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($eventId !== null) {
            $resourcePath = str_replace(
                '{' . 'eventId' . '}',
                ObjectSerializer::toPathValue($eventId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listAuditEvents
     *
     * Query audit events (JSON or CSV)
     *
     * @param  mixed|null $from start of the period (RFC 3339); defaults to 7 days before &#x60;to&#x60; (optional)
     * @param  mixed|null $to end of the period (RFC 3339); defaults to now (optional)
     * @param  string|null $subject subject (optional)
     * @param  string|null $issuerName issuerName (optional)
     * @param  string|null $action action (optional)
     * @param  string|null $outcome outcome (optional)
     * @param  string|null $resourceType resourceType (optional)
     * @param  string|null $resourceId resourceId (optional)
     * @param  int|null $personId personId (optional)
     * @param  string|null $requestId requestId (optional)
     * @param  int|null $page page (optional, default to 1)
     * @param  int|null $pageSize pageSize (optional, default to 100)
     * @param  string|null $format csv returns text/csv with one line per event (optional, default to 'json')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listAuditEvents'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \TimecardClient\Model\ListAuditEvents200Response|\TimecardClient\Model\Problem
     */
    public function listAuditEvents(
        mixed $from = null,
        mixed $to = null,
        ?string $subject = null,
        ?string $issuerName = null,
        ?string $action = null,
        ?string $outcome = null,
        ?string $resourceType = null,
        ?string $resourceId = null,
        ?int $personId = null,
        ?string $requestId = null,
        ?int $page = 1,
        ?int $pageSize = 100,
        ?string $format = 'json',
        string $contentType = self::contentTypes['listAuditEvents'][0]
    ): \TimecardClient\Model\ListAuditEvents200Response|\TimecardClient\Model\Problem
    {
        list($response) = $this->listAuditEventsWithHttpInfo($from, $to, $subject, $issuerName, $action, $outcome, $resourceType, $resourceId, $personId, $requestId, $page, $pageSize, $format, $contentType);
        return $response;
    }

    /**
     * Operation listAuditEventsWithHttpInfo
     *
     * Query audit events (JSON or CSV)
     *
     * @param  mixed|null $from start of the period (RFC 3339); defaults to 7 days before &#x60;to&#x60; (optional)
     * @param  mixed|null $to end of the period (RFC 3339); defaults to now (optional)
     * @param  string|null $subject (optional)
     * @param  string|null $issuerName (optional)
     * @param  string|null $action (optional)
     * @param  string|null $outcome (optional)
     * @param  string|null $resourceType (optional)
     * @param  string|null $resourceId (optional)
     * @param  int|null $personId (optional)
     * @param  string|null $requestId (optional)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $pageSize (optional, default to 100)
     * @param  string|null $format csv returns text/csv with one line per event (optional, default to 'json')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listAuditEvents'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \TimecardClient\Model\ListAuditEvents200Response|\TimecardClient\Model\Problem|\TimecardClient\Model\Problem|\TimecardClient\Model\Problem|\TimecardClient\Model\Problem|\TimecardClient\Model\Problem|\TimecardClient\Model\Problem|\TimecardClient\Model\Problem, HTTP status code, HTTP response headers (array of strings)
     */
    public function listAuditEventsWithHttpInfo(
        mixed $from = null,
        mixed $to = null,
        ?string $subject = null,
        ?string $issuerName = null,
        ?string $action = null,
        ?string $outcome = null,
        ?string $resourceType = null,
        ?string $resourceId = null,
        ?int $personId = null,
        ?string $requestId = null,
        ?int $page = 1,
        ?int $pageSize = 100,
        ?string $format = 'json',
        string $contentType = self::contentTypes['listAuditEvents'][0]
    ): array
    {
        $request = $this->listAuditEventsRequest($from, $to, $subject, $issuerName, $action, $outcome, $resourceType, $resourceId, $personId, $requestId, $page, $pageSize, $format, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\TimecardClient\Model\ListAuditEvents200Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\TimecardClient\Model\Problem',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\TimecardClient\Model\Problem',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\TimecardClient\Model\Problem',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\TimecardClient\Model\Problem',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\TimecardClient\Model\Problem',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\TimecardClient\Model\Problem',
                        $request,
                        $response,
                    );
                case 503:
                    return $this->handleResponseWithDataType(
                        '\TimecardClient\Model\Problem',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\TimecardClient\Model\ListAuditEvents200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TimecardClient\Model\ListAuditEvents200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TimecardClient\Model\Problem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TimecardClient\Model\Problem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TimecardClient\Model\Problem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TimecardClient\Model\Problem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TimecardClient\Model\Problem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TimecardClient\Model\Problem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TimecardClient\Model\Problem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation listAuditEventsAsync
     *
     * Query audit events (JSON or CSV)
     *
     * @param  mixed|null $from start of the period (RFC 3339); defaults to 7 days before &#x60;to&#x60; (optional)
     * @param  mixed|null $to end of the period (RFC 3339); defaults to now (optional)
     * @param  string|null $subject (optional)
     * @param  string|null $issuerName (optional)
     * @param  string|null $action (optional)
     * @param  string|null $outcome (optional)
     * @param  string|null $resourceType (optional)
     * @param  string|null $resourceId (optional)
     * @param  int|null $personId (optional)
     * @param  string|null $requestId (optional)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $pageSize (optional, default to 100)
     * @param  string|null $format csv returns text/csv with one line per event (optional, default to 'json')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listAuditEvents'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function listAuditEventsAsync(
        mixed $from = null,
        mixed $to = null,
        ?string $subject = null,
        ?string $issuerName = null,
        ?string $action = null,
        ?string $outcome = null,
        ?string $resourceType = null,
        ?string $resourceId = null,
        ?int $personId = null,
        ?string $requestId = null,
        ?int $page = 1,
        ?int $pageSize = 100,
        ?string $format = 'json',
        string $contentType = self::contentTypes['listAuditEvents'][0]
    ): PromiseInterface
    {
        return $this->listAuditEventsAsyncWithHttpInfo($from, $to, $subject, $issuerName, $action, $outcome, $resourceType, $resourceId, $personId, $requestId, $page, $pageSize, $format, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listAuditEventsAsyncWithHttpInfo
     *
     * Query audit events (JSON or CSV)
     *
     * @param  mixed|null $from start of the period (RFC 3339); defaults to 7 days before &#x60;to&#x60; (optional)
     * @param  mixed|null $to end of the period (RFC 3339); defaults to now (optional)
     * @param  string|null $subject (optional)
     * @param  string|null $issuerName (optional)
     * @param  string|null $action (optional)
     * @param  string|null $outcome (optional)
     * @param  string|null $resourceType (optional)
     * @param  string|null $resourceId (optional)
     * @param  int|null $personId (optional)
     * @param  string|null $requestId (optional)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $pageSize (optional, default to 100)
     * @param  string|null $format csv returns text/csv with one line per event (optional, default to 'json')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listAuditEvents'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function listAuditEventsAsyncWithHttpInfo(
        mixed $from = null,
        mixed $to = null,
        ?string $subject = null,
        ?string $issuerName = null,
        ?string $action = null,
        ?string $outcome = null,
        ?string $resourceType = null,
        ?string $resourceId = null,
        ?int $personId = null,
        ?string $requestId = null,
        ?int $page = 1,
        ?int $pageSize = 100,
        ?string $format = 'json',
        string $contentType = self::contentTypes['listAuditEvents'][0]
    ): PromiseInterface
    {
        $returnType = '\TimecardClient\Model\ListAuditEvents200Response';
        $request = $this->listAuditEventsRequest($from, $to, $subject, $issuerName, $action, $outcome, $resourceType, $resourceId, $personId, $requestId, $page, $pageSize, $format, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listAuditEvents'
     *
     * @param  mixed|null $from start of the period (RFC 3339); defaults to 7 days before &#x60;to&#x60; (optional)
     * @param  mixed|null $to end of the period (RFC 3339); defaults to now (optional)
     * @param  string|null $subject (optional)
     * @param  string|null $issuerName (optional)
     * @param  string|null $action (optional)
     * @param  string|null $outcome (optional)
     * @param  string|null $resourceType (optional)
     * @param  string|null $resourceId (optional)
     * @param  int|null $personId (optional)
     * @param  string|null $requestId (optional)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $pageSize (optional, default to 100)
     * @param  string|null $format csv returns text/csv with one line per event (optional, default to 'json')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listAuditEvents'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listAuditEventsRequest(
        mixed $from = null,
        mixed $to = null,
        ?string $subject = null,
        ?string $issuerName = null,
        ?string $action = null,
        ?string $outcome = null,
        ?string $resourceType = null,
        ?string $resourceId = null,
        ?int $personId = null,
        ?string $requestId = null,
        ?int $page = 1,
        ?int $pageSize = 100,
        ?string $format = 'json',
        string $contentType = self::contentTypes['listAuditEvents'][0]
    ): Request
    {









        if ($personId !== null && $personId > 9007199254740991) {
            throw new InvalidArgumentException('invalid value for "$personId" when calling AuditApi.listAuditEvents, must be smaller than or equal to 9007199254740991.');
        }
        

        if ($page !== null && $page > 9007199254740991) {
            throw new InvalidArgumentException('invalid value for "$page" when calling AuditApi.listAuditEvents, must be smaller than or equal to 9007199254740991.');
        }
        if ($page !== null && $page < 1) {
            throw new InvalidArgumentException('invalid value for "$page" when calling AuditApi.listAuditEvents, must be bigger than or equal to 1.');
        }
        
        if ($pageSize !== null && $pageSize > 1000) {
            throw new InvalidArgumentException('invalid value for "$pageSize" when calling AuditApi.listAuditEvents, must be smaller than or equal to 1000.');
        }
        if ($pageSize !== null && $pageSize < 1) {
            throw new InvalidArgumentException('invalid value for "$pageSize" when calling AuditApi.listAuditEvents, must be bigger than or equal to 1.');
        }
        


        $resourcePath = '/v1/audit-events';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $from,
            'from', // param base name
            'mixed', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $to,
            'to', // param base name
            'mixed', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $subject,
            'subject', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $issuerName,
            'issuerName', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $action,
            'action', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $outcome,
            'outcome', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $resourceType,
            'resourceType', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $resourceId,
            'resourceId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $personId,
            'personId', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $requestId,
            'requestId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $pageSize,
            'pageSize', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $format,
            'format', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response,
    ): array {
        if (in_array($dataType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode,
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
