<?php
/**
 * WorkOperationsApi
 * PHP version 8.1
 *
 * @package  TimecardClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * timeCard REST facade
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.1
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TimecardClient\Api;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use TimecardClient\ApiException;
use TimecardClient\Configuration;
use TimecardClient\HeaderSelector;
use TimecardClient\FormDataProcessor;
use TimecardClient\ObjectSerializer;

/**
 * WorkOperationsApi Class Doc Comment
 *
 * @package  TimecardClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WorkOperationsApi
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createWorkOperation' => [
            'application/json',
        ],
        'deleteWorkOperation' => [
            'application/json',
        ],
        'getWorkOperation' => [
            'application/json',
        ],
        'listProjectWorkOperations' => [
            'application/json',
        ],
        'listWorkOperations' => [
            'application/json',
        ],
        'updateWorkOperation' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation createWorkOperation
     *
     * Create a work operation (timeCard user right 213 create)
     *
     * @param  \TimecardClient\Model\CreateWorkOperationRequest $create_work_operation_request create_work_operation_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createWorkOperation'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \TimecardClient\Model\CreateWorkOperation201Response
     */
    public function createWorkOperation(
        \TimecardClient\Model\CreateWorkOperationRequest $create_work_operation_request,
        string $contentType = self::contentTypes['createWorkOperation'][0]
    ): \TimecardClient\Model\CreateWorkOperation201Response
    {
        list($response) = $this->createWorkOperationWithHttpInfo($create_work_operation_request, $contentType);
        return $response;
    }

    /**
     * Operation createWorkOperationWithHttpInfo
     *
     * Create a work operation (timeCard user right 213 create)
     *
     * @param  \TimecardClient\Model\CreateWorkOperationRequest $create_work_operation_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createWorkOperation'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \TimecardClient\Model\CreateWorkOperation201Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function createWorkOperationWithHttpInfo(
        \TimecardClient\Model\CreateWorkOperationRequest $create_work_operation_request,
        string $contentType = self::contentTypes['createWorkOperation'][0]
    ): array
    {
        $request = $this->createWorkOperationRequest($create_work_operation_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\TimecardClient\Model\CreateWorkOperation201Response',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\TimecardClient\Model\CreateWorkOperation201Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TimecardClient\Model\CreateWorkOperation201Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation createWorkOperationAsync
     *
     * Create a work operation (timeCard user right 213 create)
     *
     * @param  \TimecardClient\Model\CreateWorkOperationRequest $create_work_operation_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createWorkOperation'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function createWorkOperationAsync(
        \TimecardClient\Model\CreateWorkOperationRequest $create_work_operation_request,
        string $contentType = self::contentTypes['createWorkOperation'][0]
    ): PromiseInterface
    {
        return $this->createWorkOperationAsyncWithHttpInfo($create_work_operation_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createWorkOperationAsyncWithHttpInfo
     *
     * Create a work operation (timeCard user right 213 create)
     *
     * @param  \TimecardClient\Model\CreateWorkOperationRequest $create_work_operation_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createWorkOperation'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function createWorkOperationAsyncWithHttpInfo(
        \TimecardClient\Model\CreateWorkOperationRequest $create_work_operation_request,
        string $contentType = self::contentTypes['createWorkOperation'][0]
    ): PromiseInterface
    {
        $returnType = '\TimecardClient\Model\CreateWorkOperation201Response';
        $request = $this->createWorkOperationRequest($create_work_operation_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createWorkOperation'
     *
     * @param  \TimecardClient\Model\CreateWorkOperationRequest $create_work_operation_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createWorkOperation'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createWorkOperationRequest(
        \TimecardClient\Model\CreateWorkOperationRequest $create_work_operation_request,
        string $contentType = self::contentTypes['createWorkOperation'][0]
    ): Request
    {

        // verify the required parameter 'create_work_operation_request' is set
        if ($create_work_operation_request === null || (is_array($create_work_operation_request) && count($create_work_operation_request) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $create_work_operation_request when calling createWorkOperation'
            );
        }


        $resourcePath = '/v1/work-operations';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_work_operation_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_work_operation_request));
            } else {
                $httpBody = $create_work_operation_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteWorkOperation
     *
     * Delete a work operation (timeCard user right 213 delete; a used work operation is rejected by timeCard)
     *
     * @param  int $work_operation_id work_operation_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteWorkOperation'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return void
     */
    public function deleteWorkOperation(
        int $work_operation_id,
        string $contentType = self::contentTypes['deleteWorkOperation'][0]
    ): void
    {
        $this->deleteWorkOperationWithHttpInfo($work_operation_id, $contentType);
    }

    /**
     * Operation deleteWorkOperationWithHttpInfo
     *
     * Delete a work operation (timeCard user right 213 delete; a used work operation is rejected by timeCard)
     *
     * @param  int $work_operation_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteWorkOperation'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteWorkOperationWithHttpInfo(
        int $work_operation_id,
        string $contentType = self::contentTypes['deleteWorkOperation'][0]
    ): array
    {
        $request = $this->deleteWorkOperationRequest($work_operation_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        
            throw $e;
        }
    }

    /**
     * Operation deleteWorkOperationAsync
     *
     * Delete a work operation (timeCard user right 213 delete; a used work operation is rejected by timeCard)
     *
     * @param  int $work_operation_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteWorkOperation'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function deleteWorkOperationAsync(
        int $work_operation_id,
        string $contentType = self::contentTypes['deleteWorkOperation'][0]
    ): PromiseInterface
    {
        return $this->deleteWorkOperationAsyncWithHttpInfo($work_operation_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteWorkOperationAsyncWithHttpInfo
     *
     * Delete a work operation (timeCard user right 213 delete; a used work operation is rejected by timeCard)
     *
     * @param  int $work_operation_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteWorkOperation'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function deleteWorkOperationAsyncWithHttpInfo(
        int $work_operation_id,
        string $contentType = self::contentTypes['deleteWorkOperation'][0]
    ): PromiseInterface
    {
        $returnType = '';
        $request = $this->deleteWorkOperationRequest($work_operation_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteWorkOperation'
     *
     * @param  int $work_operation_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteWorkOperation'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteWorkOperationRequest(
        int $work_operation_id,
        string $contentType = self::contentTypes['deleteWorkOperation'][0]
    ): Request
    {

        // verify the required parameter 'work_operation_id' is set
        if ($work_operation_id === null || (is_array($work_operation_id) && count($work_operation_id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $work_operation_id when calling deleteWorkOperation'
            );
        }
        if ($work_operation_id > 9007199254740991) {
            throw new InvalidArgumentException('invalid value for "$work_operation_id" when calling WorkOperationsApi.deleteWorkOperation, must be smaller than or equal to 9007199254740991.');
        }
        

        $resourcePath = '/v1/work-operations/{workOperationId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($work_operation_id !== null) {
            $resourcePath = str_replace(
                '{' . 'workOperationId' . '}',
                ObjectSerializer::toPathValue($work_operation_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getWorkOperation
     *
     * Work operation details
     *
     * @param  int $work_operation_id work_operation_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getWorkOperation'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \TimecardClient\Model\CreateWorkOperation201Response
     */
    public function getWorkOperation(
        int $work_operation_id,
        string $contentType = self::contentTypes['getWorkOperation'][0]
    ): \TimecardClient\Model\CreateWorkOperation201Response
    {
        list($response) = $this->getWorkOperationWithHttpInfo($work_operation_id, $contentType);
        return $response;
    }

    /**
     * Operation getWorkOperationWithHttpInfo
     *
     * Work operation details
     *
     * @param  int $work_operation_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getWorkOperation'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \TimecardClient\Model\CreateWorkOperation201Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getWorkOperationWithHttpInfo(
        int $work_operation_id,
        string $contentType = self::contentTypes['getWorkOperation'][0]
    ): array
    {
        $request = $this->getWorkOperationRequest($work_operation_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\TimecardClient\Model\CreateWorkOperation201Response',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\TimecardClient\Model\CreateWorkOperation201Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TimecardClient\Model\CreateWorkOperation201Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation getWorkOperationAsync
     *
     * Work operation details
     *
     * @param  int $work_operation_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getWorkOperation'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getWorkOperationAsync(
        int $work_operation_id,
        string $contentType = self::contentTypes['getWorkOperation'][0]
    ): PromiseInterface
    {
        return $this->getWorkOperationAsyncWithHttpInfo($work_operation_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getWorkOperationAsyncWithHttpInfo
     *
     * Work operation details
     *
     * @param  int $work_operation_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getWorkOperation'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getWorkOperationAsyncWithHttpInfo(
        int $work_operation_id,
        string $contentType = self::contentTypes['getWorkOperation'][0]
    ): PromiseInterface
    {
        $returnType = '\TimecardClient\Model\CreateWorkOperation201Response';
        $request = $this->getWorkOperationRequest($work_operation_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getWorkOperation'
     *
     * @param  int $work_operation_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getWorkOperation'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getWorkOperationRequest(
        int $work_operation_id,
        string $contentType = self::contentTypes['getWorkOperation'][0]
    ): Request
    {

        // verify the required parameter 'work_operation_id' is set
        if ($work_operation_id === null || (is_array($work_operation_id) && count($work_operation_id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $work_operation_id when calling getWorkOperation'
            );
        }
        if ($work_operation_id > 9007199254740991) {
            throw new InvalidArgumentException('invalid value for "$work_operation_id" when calling WorkOperationsApi.getWorkOperation, must be smaller than or equal to 9007199254740991.');
        }
        

        $resourcePath = '/v1/work-operations/{workOperationId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($work_operation_id !== null) {
            $resourcePath = str_replace(
                '{' . 'workOperationId' . '}',
                ObjectSerializer::toPathValue($work_operation_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listProjectWorkOperations
     *
     * Work operations allowed for a project
     *
     * @param  int $project_id project_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listProjectWorkOperations'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \TimecardClient\Model\ListProjectWorkOperations200Response
     */
    public function listProjectWorkOperations(
        int $project_id,
        string $contentType = self::contentTypes['listProjectWorkOperations'][0]
    ): \TimecardClient\Model\ListProjectWorkOperations200Response
    {
        list($response) = $this->listProjectWorkOperationsWithHttpInfo($project_id, $contentType);
        return $response;
    }

    /**
     * Operation listProjectWorkOperationsWithHttpInfo
     *
     * Work operations allowed for a project
     *
     * @param  int $project_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listProjectWorkOperations'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \TimecardClient\Model\ListProjectWorkOperations200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function listProjectWorkOperationsWithHttpInfo(
        int $project_id,
        string $contentType = self::contentTypes['listProjectWorkOperations'][0]
    ): array
    {
        $request = $this->listProjectWorkOperationsRequest($project_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\TimecardClient\Model\ListProjectWorkOperations200Response',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\TimecardClient\Model\ListProjectWorkOperations200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TimecardClient\Model\ListProjectWorkOperations200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation listProjectWorkOperationsAsync
     *
     * Work operations allowed for a project
     *
     * @param  int $project_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listProjectWorkOperations'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function listProjectWorkOperationsAsync(
        int $project_id,
        string $contentType = self::contentTypes['listProjectWorkOperations'][0]
    ): PromiseInterface
    {
        return $this->listProjectWorkOperationsAsyncWithHttpInfo($project_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listProjectWorkOperationsAsyncWithHttpInfo
     *
     * Work operations allowed for a project
     *
     * @param  int $project_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listProjectWorkOperations'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function listProjectWorkOperationsAsyncWithHttpInfo(
        int $project_id,
        string $contentType = self::contentTypes['listProjectWorkOperations'][0]
    ): PromiseInterface
    {
        $returnType = '\TimecardClient\Model\ListProjectWorkOperations200Response';
        $request = $this->listProjectWorkOperationsRequest($project_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listProjectWorkOperations'
     *
     * @param  int $project_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listProjectWorkOperations'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listProjectWorkOperationsRequest(
        int $project_id,
        string $contentType = self::contentTypes['listProjectWorkOperations'][0]
    ): Request
    {

        // verify the required parameter 'project_id' is set
        if ($project_id === null || (is_array($project_id) && count($project_id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $project_id when calling listProjectWorkOperations'
            );
        }
        if ($project_id > 9007199254740991) {
            throw new InvalidArgumentException('invalid value for "$project_id" when calling WorkOperationsApi.listProjectWorkOperations, must be smaller than or equal to 9007199254740991.');
        }
        

        $resourcePath = '/v1/projects/{projectId}/work-operations';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($project_id !== null) {
            $resourcePath = str_replace(
                '{' . 'projectId' . '}',
                ObjectSerializer::toPathValue($project_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listWorkOperations
     *
     * All work operations
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listWorkOperations'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \TimecardClient\Model\ListProjectWorkOperations200Response
     */
    public function listWorkOperations(
        string $contentType = self::contentTypes['listWorkOperations'][0]
    ): \TimecardClient\Model\ListProjectWorkOperations200Response
    {
        list($response) = $this->listWorkOperationsWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation listWorkOperationsWithHttpInfo
     *
     * All work operations
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listWorkOperations'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \TimecardClient\Model\ListProjectWorkOperations200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function listWorkOperationsWithHttpInfo(
        string $contentType = self::contentTypes['listWorkOperations'][0]
    ): array
    {
        $request = $this->listWorkOperationsRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\TimecardClient\Model\ListProjectWorkOperations200Response',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\TimecardClient\Model\ListProjectWorkOperations200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TimecardClient\Model\ListProjectWorkOperations200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation listWorkOperationsAsync
     *
     * All work operations
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listWorkOperations'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function listWorkOperationsAsync(
        string $contentType = self::contentTypes['listWorkOperations'][0]
    ): PromiseInterface
    {
        return $this->listWorkOperationsAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listWorkOperationsAsyncWithHttpInfo
     *
     * All work operations
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listWorkOperations'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function listWorkOperationsAsyncWithHttpInfo(
        string $contentType = self::contentTypes['listWorkOperations'][0]
    ): PromiseInterface
    {
        $returnType = '\TimecardClient\Model\ListProjectWorkOperations200Response';
        $request = $this->listWorkOperationsRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listWorkOperations'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listWorkOperations'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listWorkOperationsRequest(
        string $contentType = self::contentTypes['listWorkOperations'][0]
    ): Request
    {


        $resourcePath = '/v1/work-operations';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateWorkOperation
     *
     * Change a work operation (read-modify-write, timeCard user right 213 update)
     *
     * @param  int $work_operation_id work_operation_id (required)
     * @param  \TimecardClient\Model\UpdateWorkOperationRequest $update_work_operation_request update_work_operation_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateWorkOperation'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \TimecardClient\Model\CreateWorkOperation201Response
     */
    public function updateWorkOperation(
        int $work_operation_id,
        \TimecardClient\Model\UpdateWorkOperationRequest $update_work_operation_request,
        string $contentType = self::contentTypes['updateWorkOperation'][0]
    ): \TimecardClient\Model\CreateWorkOperation201Response
    {
        list($response) = $this->updateWorkOperationWithHttpInfo($work_operation_id, $update_work_operation_request, $contentType);
        return $response;
    }

    /**
     * Operation updateWorkOperationWithHttpInfo
     *
     * Change a work operation (read-modify-write, timeCard user right 213 update)
     *
     * @param  int $work_operation_id (required)
     * @param  \TimecardClient\Model\UpdateWorkOperationRequest $update_work_operation_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateWorkOperation'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \TimecardClient\Model\CreateWorkOperation201Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateWorkOperationWithHttpInfo(
        int $work_operation_id,
        \TimecardClient\Model\UpdateWorkOperationRequest $update_work_operation_request,
        string $contentType = self::contentTypes['updateWorkOperation'][0]
    ): array
    {
        $request = $this->updateWorkOperationRequest($work_operation_id, $update_work_operation_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\TimecardClient\Model\CreateWorkOperation201Response',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\TimecardClient\Model\CreateWorkOperation201Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TimecardClient\Model\CreateWorkOperation201Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation updateWorkOperationAsync
     *
     * Change a work operation (read-modify-write, timeCard user right 213 update)
     *
     * @param  int $work_operation_id (required)
     * @param  \TimecardClient\Model\UpdateWorkOperationRequest $update_work_operation_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateWorkOperation'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function updateWorkOperationAsync(
        int $work_operation_id,
        \TimecardClient\Model\UpdateWorkOperationRequest $update_work_operation_request,
        string $contentType = self::contentTypes['updateWorkOperation'][0]
    ): PromiseInterface
    {
        return $this->updateWorkOperationAsyncWithHttpInfo($work_operation_id, $update_work_operation_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateWorkOperationAsyncWithHttpInfo
     *
     * Change a work operation (read-modify-write, timeCard user right 213 update)
     *
     * @param  int $work_operation_id (required)
     * @param  \TimecardClient\Model\UpdateWorkOperationRequest $update_work_operation_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateWorkOperation'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function updateWorkOperationAsyncWithHttpInfo(
        int $work_operation_id,
        \TimecardClient\Model\UpdateWorkOperationRequest $update_work_operation_request,
        string $contentType = self::contentTypes['updateWorkOperation'][0]
    ): PromiseInterface
    {
        $returnType = '\TimecardClient\Model\CreateWorkOperation201Response';
        $request = $this->updateWorkOperationRequest($work_operation_id, $update_work_operation_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateWorkOperation'
     *
     * @param  int $work_operation_id (required)
     * @param  \TimecardClient\Model\UpdateWorkOperationRequest $update_work_operation_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateWorkOperation'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateWorkOperationRequest(
        int $work_operation_id,
        \TimecardClient\Model\UpdateWorkOperationRequest $update_work_operation_request,
        string $contentType = self::contentTypes['updateWorkOperation'][0]
    ): Request
    {

        // verify the required parameter 'work_operation_id' is set
        if ($work_operation_id === null || (is_array($work_operation_id) && count($work_operation_id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $work_operation_id when calling updateWorkOperation'
            );
        }
        if ($work_operation_id > 9007199254740991) {
            throw new InvalidArgumentException('invalid value for "$work_operation_id" when calling WorkOperationsApi.updateWorkOperation, must be smaller than or equal to 9007199254740991.');
        }
        
        // verify the required parameter 'update_work_operation_request' is set
        if ($update_work_operation_request === null || (is_array($update_work_operation_request) && count($update_work_operation_request) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $update_work_operation_request when calling updateWorkOperation'
            );
        }


        $resourcePath = '/v1/work-operations/{workOperationId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($work_operation_id !== null) {
            $resourcePath = str_replace(
                '{' . 'workOperationId' . '}',
                ObjectSerializer::toPathValue($work_operation_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($update_work_operation_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($update_work_operation_request));
            } else {
                $httpBody = $update_work_operation_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response,
    ): array {
        if (in_array($dataType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode,
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
